//
// Copyright (C) 2019-2026 vdaas.org vald team <vald@vdaas.org>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Package valdrelease defines the ValdRelease API model generated by the operator.
package valdrelease

import (
	"github.com/vdaas/vald/internal/k8s/resource"
	"github.com/vdaas/vald/internal/k8s/vald/operator/api/valdrelease/agent"
	"github.com/vdaas/vald/internal/k8s/vald/operator/api/valdrelease/defaults"
	"github.com/vdaas/vald/internal/k8s/vald/operator/api/valdrelease/discoverer"
	"github.com/vdaas/vald/internal/k8s/vald/operator/api/valdrelease/gateway"
	"github.com/vdaas/vald/internal/k8s/vald/operator/api/valdrelease/manager"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

var (
	GroupVersion = schema.GroupVersion{Group: "vald.vdaas.org", Version: "v1"}

	// SchemeBuilder registers the item type via AddKnownTypes and the generic
	// list alias via AddListToScheme: generic instantiations carry mangled
	// reflect type names, so the list kind must be registered explicitly.
	SchemeBuilder = runtime.NewSchemeBuilder(func(s *runtime.Scheme) error {
		s.AddKnownTypes(GroupVersion, &ValdRelease{})
		resource.AddListToScheme[ValdRelease](s, GroupVersion, "ValdReleaseList")
		metav1.AddToGroupVersion(s, GroupVersion)
		return nil
	})

	AddToScheme = SchemeBuilder.AddToScheme
)

var GVK = schema.GroupVersionKind{
	Group:   GroupVersion.Group,
	Version: GroupVersion.Version,
	Kind:    "ValdRelease",
}

type ValdRelease struct {
	resource.Base[ValdRelease, *ValdRelease] `json:"-"`

	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata"`

	Spec   Spec      `json:"spec"`
	Status VrsStatus `json:"status"`
}

// ValdReleaseList contains a list of ValdRelease. The whole list kind is
// derived generically from the item type.
type ValdReleaseList = resource.List[ValdRelease, *ValdRelease]

type Spec struct {
	Defaults   defaults.Defaults     `json:"defaults"`
	Gateway    gateway.Gateway       `json:"gateway"`
	Agent      agent.Agent           `json:"agent"`
	Manager    manager.Manager       `json:"manager"`
	Discoverer discoverer.Discoverer `json:"discoverer"`
}

type VrsStatus struct {
	Condition metav1.Condition `json:"condition"`
}
