apiVersion: vald.vdaas.org/v1
kind: ValdRelease
metadata:
  name: vald-cluster
spec:
  defaults:
    image:
      tag: nightly
      pullPolicy: IfNotPresent
    time_zone: Asia/Tokyo
    logging:
      format: raw
      level: info
      logger: glg
    server_config:
      servers:
        grpc:
          server:
            grpc:
              interceptors:
                - "RecoverInterceptor"
                - "MetricInterceptor"
    observability:
      enabled: true
      trace:
        enabled: false
      otlp:
        collector_endpoint: "otel-collector.monitoring.svc.cluster.local:4317"
  discoverer:
    image:
      pullPolicy: IfNotPresent
    logging:
      level: warn
    discoverer:
      discovery_duration: 200ms
    resources:
      limits:
        memory: 300Mi
      requests:
        memory: 160Mi
  manager:
    image:
      pullPolicy: IfNotPresent
    index:
      image:
        pullPolicy: IfNotPresent
      saver:
        image:
          pullPolicy: IfNotPresent
      creator:
        image:
          pullPolicy: IfNotPresent
      logging:
        level: warn
  gateway:
    lb:
      image:
        pullPolicy: IfNotPresent
      enabled: true
      rollingUpdate:
        maxSurge: "25%"
        maxUnavailable: "10%"
      hpa:
        targetCPUUtilizationPercentage: 50
      ingress:
        enabled: false
        defaultBackend:
          enabled: false
      gateway_config:
        index_replica: 1
  agent:
    image:
      pullPolicy: IfNotPresent
    hpa:
      enabled: false
    rollingUpdate:
      maxSurge: "1"
      maxUnavailable: "1"
    minReplicas: 3
    maxReplicas: 3
    terminationGracePeriodSeconds: 2400
    ngt:
      auto_index_check_duration: "-1h"
      auto_index_duration_limit: "-1h"
      auto_save_index_duration: "-1h"
      bulk_insert_chunk_size: 10
      dimension: 2
      distance_type: l2
      object_type: float
      enable_in_memory_mode: true
    podManagementPolicy: Parallel