//go:build !ignore_autogenerated

//
// Copyright (C) 2019-2026 vdaas.org vald team <vald@vdaas.org>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Agent) DeepCopyInto(out *Agent) {
	*out = *in
	out.Ngt = in.Ngt
	if in.PersistentVolume != nil {
		in, out := &in.PersistentVolume, &out.PersistentVolume
		*out = new(AgentPersistentVolume)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Agent.
func (in *Agent) DeepCopy() *Agent {
	if in == nil {
		return nil
	}
	out := new(Agent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPersistentVolume) DeepCopyInto(out *AgentPersistentVolume) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPersistentVolume.
func (in *AgentPersistentVolume) DeepCopy() *AgentPersistentVolume {
	if in == nil {
		return nil
	}
	out := new(AgentPersistentVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyzedLog) DeepCopyInto(out *AnalyzedLog) {
	*out = *in
	in.Date.DeepCopyInto(&out.Date)
	if in.Details != nil {
		in, out := &in.Details, &out.Details
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyzedLog.
func (in *AnalyzedLog) DeepCopy() *AnalyzedLog {
	if in == nil {
		return nil
	}
	out := new(AnalyzedLog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DestClusters) DeepCopyInto(out *DestClusters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DestClusters.
func (in *DestClusters) DeepCopy() *DestClusters {
	if in == nil {
		return nil
	}
	out := new(DestClusters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Discoverer) DeepCopyInto(out *Discoverer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Discoverer.
func (in *Discoverer) DeepCopy() *Discoverer {
	if in == nil {
		return nil
	}
	out := new(Discoverer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Gateway) DeepCopyInto(out *Gateway) {
	*out = *in
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(GatewayIngress)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Gateway.
func (in *Gateway) DeepCopy() *Gateway {
	if in == nil {
		return nil
	}
	out := new(Gateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayIngress) DeepCopyInto(out *GatewayIngress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayIngress.
func (in *GatewayIngress) DeepCopy() *GatewayIngress {
	if in == nil {
		return nil
	}
	out := new(GatewayIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Indexer) DeepCopyInto(out *Indexer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Indexer.
func (in *Indexer) DeepCopy() *Indexer {
	if in == nil {
		return nil
	}
	out := new(Indexer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineResource) DeepCopyInto(out *MachineResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineResource.
func (in *MachineResource) DeepCopy() *MachineResource {
	if in == nil {
		return nil
	}
	out := new(MachineResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValdOperatorRelease) DeepCopyInto(out *ValdOperatorRelease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValdOperatorRelease.
func (in *ValdOperatorRelease) DeepCopy() *ValdOperatorRelease {
	if in == nil {
		return nil
	}
	out := new(ValdOperatorRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ValdOperatorRelease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValdOperatorReleaseInfra) DeepCopyInto(out *ValdOperatorReleaseInfra) {
	*out = *in
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]DestClusters, len(*in))
		copy(*out, *in)
	}
	if in.NodePools != nil {
		in, out := &in.NodePools, &out.NodePools
		*out = make(NodePools, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValdOperatorReleaseInfra.
func (in *ValdOperatorReleaseInfra) DeepCopy() *ValdOperatorReleaseInfra {
	if in == nil {
		return nil
	}
	out := new(ValdOperatorReleaseInfra)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValdOperatorReleaseList) DeepCopyInto(out *ValdOperatorReleaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ValdOperatorRelease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValdOperatorReleaseList.
func (in *ValdOperatorReleaseList) DeepCopy() *ValdOperatorReleaseList {
	if in == nil {
		return nil
	}
	out := new(ValdOperatorReleaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ValdOperatorReleaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValdOperatorReleaseSpec) DeepCopyInto(out *ValdOperatorReleaseSpec) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = make([]ValdOperatorReleaseInfra, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.VectorEngine.DeepCopyInto(&out.VectorEngine)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValdOperatorReleaseSpec.
func (in *ValdOperatorReleaseSpec) DeepCopy() *ValdOperatorReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(ValdOperatorReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValdOperatorReleaseStatus) DeepCopyInto(out *ValdOperatorReleaseStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Progress = in.Progress
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValdOperatorReleaseStatus.
func (in *ValdOperatorReleaseStatus) DeepCopy() *ValdOperatorReleaseStatus {
	if in == nil {
		return nil
	}
	out := new(ValdOperatorReleaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ngt) DeepCopyInto(out *Ngt) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ngt.
func (in *Ngt) DeepCopy() *Ngt {
	if in == nil {
		return nil
	}
	out := new(Ngt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePool) DeepCopyInto(out *NodePool) {
	*out = *in
	out.MachineResource = in.MachineResource
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePool.
func (in *NodePool) DeepCopy() *NodePool {
	if in == nil {
		return nil
	}
	out := new(NodePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in NodePools) DeepCopyInto(out *NodePools) {
	{
		in := &in
		*out = make(NodePools, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePools.
func (in NodePools) DeepCopy() NodePools {
	if in == nil {
		return nil
	}
	out := new(NodePools)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Progress) DeepCopyInto(out *Progress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Progress.
func (in *Progress) DeepCopy() *Progress {
	if in == nil {
		return nil
	}
	out := new(Progress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Vald) DeepCopyInto(out *Vald) {
	*out = *in
	out.Defaults = in.Defaults
	in.Agent.DeepCopyInto(&out.Agent)
	out.Indexer = in.Indexer
	in.Gateway.DeepCopyInto(&out.Gateway)
	out.Discoverer = in.Discoverer
	in.Overlay.DeepCopyInto(&out.Overlay)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Vald.
func (in *Vald) DeepCopy() *Vald {
	if in == nil {
		return nil
	}
	out := new(Vald)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValdDefaults) DeepCopyInto(out *ValdDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValdDefaults.
func (in *ValdDefaults) DeepCopy() *ValdDefaults {
	if in == nil {
		return nil
	}
	out := new(ValdDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VectorEngine) DeepCopyInto(out *VectorEngine) {
	*out = *in
	in.Vald.DeepCopyInto(&out.Vald)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VectorEngine.
func (in *VectorEngine) DeepCopy() *VectorEngine {
	if in == nil {
		return nil
	}
	out := new(VectorEngine)
	in.DeepCopyInto(out)
	return out
}
