//
// Copyright (C) 2019-2025 vdaas.org vald team <vald@vdaas.org>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/vald/filter.proto

package vald

import (
	reflect "reflect"
	unsafe "unsafe"

	payload "github.com/vdaas/vald/apis/grpc/v1/payload"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_v1_vald_filter_proto protoreflect.FileDescriptor

const file_v1_vald_filter_proto_rawDesc = "" +
	"\n" +
	"\x14v1/vald/filter.proto\x12\avald.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x18v1/payload/payload.proto2\xac\n" +
	"\n" +
	"\x06Filter\x12h\n" +
	"\fSearchObject\x12 .payload.v1.Search.ObjectRequest\x1a\x1b.payload.v1.Search.Response\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/search/object\x12|\n" +
	"\x11MultiSearchObject\x12%.payload.v1.Search.MultiObjectRequest\x1a\x1c.payload.v1.Search.Responses\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/search/object/multiple\x12_\n" +
	"\x12StreamSearchObject\x12 .payload.v1.Search.ObjectRequest\x1a!.payload.v1.Search.StreamResponse\"\x00(\x010\x01\x12h\n" +
	"\fInsertObject\x12 .payload.v1.Insert.ObjectRequest\x1a\x1b.payload.v1.Object.Location\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/insert/object\x12_\n" +
	"\x12StreamInsertObject\x12 .payload.v1.Insert.ObjectRequest\x1a!.payload.v1.Object.StreamLocation\"\x00(\x010\x01\x12|\n" +
	"\x11MultiInsertObject\x12%.payload.v1.Insert.MultiObjectRequest\x1a\x1c.payload.v1.Object.Locations\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/insert/object/multiple\x12h\n" +
	"\fUpdateObject\x12 .payload.v1.Update.ObjectRequest\x1a\x1b.payload.v1.Object.Location\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/update/object\x12_\n" +
	"\x12StreamUpdateObject\x12 .payload.v1.Update.ObjectRequest\x1a!.payload.v1.Object.StreamLocation\"\x00(\x010\x01\x12|\n" +
	"\x11MultiUpdateObject\x12%.payload.v1.Update.MultiObjectRequest\x1a\x1c.payload.v1.Object.Locations\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/update/object/multiple\x12h\n" +
	"\fUpsertObject\x12 .payload.v1.Upsert.ObjectRequest\x1a\x1b.payload.v1.Object.Location\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/upsert/object\x12_\n" +
	"\x12StreamUpsertObject\x12 .payload.v1.Upsert.ObjectRequest\x1a!.payload.v1.Object.StreamLocation\"\x00(\x010\x01\x12|\n" +
	"\x11MultiUpsertObject\x12%.payload.v1.Upsert.MultiObjectRequest\x1a\x1c.payload.v1.Object.Locations\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/upsert/object/multipleBS\n" +
	"\x1aorg.vdaas.vald.api.v1.valdB\n" +
	"ValdFilterP\x01Z'github.com/vdaas/vald/apis/grpc/v1/valdb\x06proto3"

var file_v1_vald_filter_proto_goTypes = []any{
	(*payload.Search_ObjectRequest)(nil),      // 0: payload.v1.Search.ObjectRequest
	(*payload.Search_MultiObjectRequest)(nil), // 1: payload.v1.Search.MultiObjectRequest
	(*payload.Insert_ObjectRequest)(nil),      // 2: payload.v1.Insert.ObjectRequest
	(*payload.Insert_MultiObjectRequest)(nil), // 3: payload.v1.Insert.MultiObjectRequest
	(*payload.Update_ObjectRequest)(nil),      // 4: payload.v1.Update.ObjectRequest
	(*payload.Update_MultiObjectRequest)(nil), // 5: payload.v1.Update.MultiObjectRequest
	(*payload.Upsert_ObjectRequest)(nil),      // 6: payload.v1.Upsert.ObjectRequest
	(*payload.Upsert_MultiObjectRequest)(nil), // 7: payload.v1.Upsert.MultiObjectRequest
	(*payload.Search_Response)(nil),           // 8: payload.v1.Search.Response
	(*payload.Search_Responses)(nil),          // 9: payload.v1.Search.Responses
	(*payload.Search_StreamResponse)(nil),     // 10: payload.v1.Search.StreamResponse
	(*payload.Object_Location)(nil),           // 11: payload.v1.Object.Location
	(*payload.Object_StreamLocation)(nil),     // 12: payload.v1.Object.StreamLocation
	(*payload.Object_Locations)(nil),          // 13: payload.v1.Object.Locations
}

var file_v1_vald_filter_proto_depIdxs = []int32{
	0,  // 0: vald.v1.Filter.SearchObject:input_type -> payload.v1.Search.ObjectRequest
	1,  // 1: vald.v1.Filter.MultiSearchObject:input_type -> payload.v1.Search.MultiObjectRequest
	0,  // 2: vald.v1.Filter.StreamSearchObject:input_type -> payload.v1.Search.ObjectRequest
	2,  // 3: vald.v1.Filter.InsertObject:input_type -> payload.v1.Insert.ObjectRequest
	2,  // 4: vald.v1.Filter.StreamInsertObject:input_type -> payload.v1.Insert.ObjectRequest
	3,  // 5: vald.v1.Filter.MultiInsertObject:input_type -> payload.v1.Insert.MultiObjectRequest
	4,  // 6: vald.v1.Filter.UpdateObject:input_type -> payload.v1.Update.ObjectRequest
	4,  // 7: vald.v1.Filter.StreamUpdateObject:input_type -> payload.v1.Update.ObjectRequest
	5,  // 8: vald.v1.Filter.MultiUpdateObject:input_type -> payload.v1.Update.MultiObjectRequest
	6,  // 9: vald.v1.Filter.UpsertObject:input_type -> payload.v1.Upsert.ObjectRequest
	6,  // 10: vald.v1.Filter.StreamUpsertObject:input_type -> payload.v1.Upsert.ObjectRequest
	7,  // 11: vald.v1.Filter.MultiUpsertObject:input_type -> payload.v1.Upsert.MultiObjectRequest
	8,  // 12: vald.v1.Filter.SearchObject:output_type -> payload.v1.Search.Response
	9,  // 13: vald.v1.Filter.MultiSearchObject:output_type -> payload.v1.Search.Responses
	10, // 14: vald.v1.Filter.StreamSearchObject:output_type -> payload.v1.Search.StreamResponse
	11, // 15: vald.v1.Filter.InsertObject:output_type -> payload.v1.Object.Location
	12, // 16: vald.v1.Filter.StreamInsertObject:output_type -> payload.v1.Object.StreamLocation
	13, // 17: vald.v1.Filter.MultiInsertObject:output_type -> payload.v1.Object.Locations
	11, // 18: vald.v1.Filter.UpdateObject:output_type -> payload.v1.Object.Location
	12, // 19: vald.v1.Filter.StreamUpdateObject:output_type -> payload.v1.Object.StreamLocation
	13, // 20: vald.v1.Filter.MultiUpdateObject:output_type -> payload.v1.Object.Locations
	11, // 21: vald.v1.Filter.UpsertObject:output_type -> payload.v1.Object.Location
	12, // 22: vald.v1.Filter.StreamUpsertObject:output_type -> payload.v1.Object.StreamLocation
	13, // 23: vald.v1.Filter.MultiUpsertObject:output_type -> payload.v1.Object.Locations
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_v1_vald_filter_proto_init() }
func file_v1_vald_filter_proto_init() {
	if File_v1_vald_filter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_vald_filter_proto_rawDesc), len(file_v1_vald_filter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_vald_filter_proto_goTypes,
		DependencyIndexes: file_v1_vald_filter_proto_depIdxs,
	}.Build()
	File_v1_vald_filter_proto = out.File
	file_v1_vald_filter_proto_goTypes = nil
	file_v1_vald_filter_proto_depIdxs = nil
}
