//
// Copyright (C) 2019-2026 vdaas.org vald team <vald@vdaas.org>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/vald/meta.proto

package metadata

import (
	reflect "reflect"
	unsafe "unsafe"

	payload "github.com/vdaas/vald/apis/grpc/v1/payload"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_v1_vald_meta_proto protoreflect.FileDescriptor

const file_v1_vald_meta_proto_rawDesc = "" +
	"\n" +
	"\x12v1/vald/meta.proto\x12\ameta.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x18v1/payload/payload.proto2\xb7\v\n" +
	"\x12SearchWithMetadata\x12j\n" +
	"\x12SearchWithMetadata\x12\x1a.payload.v1.Search.Request\x1a\x1b.payload.v1.Search.Response\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/search/metadata\x12s\n" +
	"\x16SearchByIDWithMetadata\x12\x1c.payload.v1.Search.IDRequest\x1a\x1b.payload.v1.Search.Response\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/search/id/metadata\x12_\n" +
	"\x18StreamSearchWithMetadata\x12\x1a.payload.v1.Search.Request\x1a!.payload.v1.Search.StreamResponse\"\x00(\x010\x01\x12e\n" +
	"\x1cStreamSearchByIDWithMetadata\x12\x1c.payload.v1.Search.IDRequest\x1a!.payload.v1.Search.StreamResponse\"\x00(\x010\x01\x12~\n" +
	"\x17MultiSearchWithMetadata\x12\x1f.payload.v1.Search.MultiRequest\x1a\x1c.payload.v1.Search.Responses\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/search/multiple/metadata\x12\x87\x01\n" +
	"\x1bMultiSearchByIDWithMetadata\x12!.payload.v1.Search.MultiIDRequest\x1a\x1c.payload.v1.Search.Responses\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/search/id/multiple/metadata\x12v\n" +
	"\x18LinearSearchWithMetadata\x12\x1a.payload.v1.Search.Request\x1a\x1b.payload.v1.Search.Response\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/linearsearch/metadata\x12\x7f\n" +
	"\x1cLinearSearchByIDWithMetadata\x12\x1c.payload.v1.Search.IDRequest\x1a\x1b.payload.v1.Search.Response\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/linearsearch/id/metadata\x12e\n" +
	"\x1eStreamLinearSearchWithMetadata\x12\x1a.payload.v1.Search.Request\x1a!.payload.v1.Search.StreamResponse\"\x00(\x010\x01\x12k\n" +
	"\"StreamLinearSearchByIDWithMetadata\x12\x1c.payload.v1.Search.IDRequest\x1a!.payload.v1.Search.StreamResponse\"\x00(\x010\x01\x12\x8a\x01\n" +
	"\x1dMultiLinearSearchWithMetadata\x12\x1f.payload.v1.Search.MultiRequest\x1a\x1c.payload.v1.Search.Responses\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/linearsearch/multiple/metadata\x12\x93\x01\n" +
	"!MultiLinearSearchByIDWithMetadata\x12!.payload.v1.Search.MultiIDRequest\x1a\x1c.payload.v1.Search.Responses\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/linearsearch/id/multiple/metadata2\xe1\x02\n" +
	"\x12InsertWithMetadata\x12j\n" +
	"\x12InsertWithMetadata\x12\x1a.payload.v1.Insert.Request\x1a\x1b.payload.v1.Object.Location\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/insert/metadata\x12_\n" +
	"\x18StreamInsertWithMetadata\x12\x1a.payload.v1.Insert.Request\x1a!.payload.v1.Object.StreamLocation\"\x00(\x010\x01\x12~\n" +
	"\x17MultiInsertWithMetadata\x12\x1f.payload.v1.Insert.MultiRequest\x1a\x1c.payload.v1.Object.Locations\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/insert/multiple/metadata2\xf9\x02\n" +
	"\x12ObjectWithMetadata\x12v\n" +
	"\x15GetObjectWithMetadata\x12 .payload.v1.Object.VectorRequest\x1a\x19.payload.v1.Object.Vector\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/object/{id.id}/metadata\x12f\n" +
	"\x1bStreamGetObjectWithMetadata\x12 .payload.v1.Object.VectorRequest\x1a\x1f.payload.v1.Object.StreamVector\"\x00(\x010\x01\x12\x82\x01\n" +
	"\x1cStreamListObjectWithMetadata\x12\x1f.payload.v1.Object.List.Request\x1a .payload.v1.Object.List.Response\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/object/list/metadata0\x012\xed\x03\n" +
	"\x12RemoveWithMetadata\x12j\n" +
	"\x12RemoveWithMetadata\x12\x1a.payload.v1.Remove.Request\x1a\x1b.payload.v1.Object.Location\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/remove/metadata\x12\x89\x01\n" +
	"\x1dRemoveByTimestampWithMetadata\x12#.payload.v1.Remove.TimestampRequest\x1a\x1c.payload.v1.Object.Locations\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/remove/timestamp/metadata\x12_\n" +
	"\x18StreamRemoveWithMetadata\x12\x1a.payload.v1.Remove.Request\x1a!.payload.v1.Object.StreamLocation\"\x00(\x010\x01\x12~\n" +
	"\x17MultiRemoveWithMetadata\x12\x1f.payload.v1.Remove.MultiRequest\x1a\x1c.payload.v1.Object.Locations\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/remove/multiple/metadata2\xea\x03\n" +
	"\x12UpdateWithMetadata\x12j\n" +
	"\x12UpdateWithMetadata\x12\x1a.payload.v1.Update.Request\x1a\x1b.payload.v1.Object.Location\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/update/metadata\x12_\n" +
	"\x18StreamUpdateWithMetadata\x12\x1a.payload.v1.Update.Request\x1a!.payload.v1.Object.StreamLocation\"\x00(\x010\x01\x12~\n" +
	"\x17MultiUpdateWithMetadata\x12\x1f.payload.v1.Update.MultiRequest\x1a\x1c.payload.v1.Object.Locations\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/update/multiple/metadata\x12\x86\x01\n" +
	"\x1bUpdateTimestampWithMetadata\x12#.payload.v1.Update.TimestampRequest\x1a\x1b.payload.v1.Object.Location\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/update/timestamp/metadata2\xe1\x02\n" +
	"\x12UpsertWithMetadata\x12j\n" +
	"\x12UpsertWithMetadata\x12\x1a.payload.v1.Upsert.Request\x1a\x1b.payload.v1.Object.Location\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/upsert/metadata\x12_\n" +
	"\x18StreamUpsertWithMetadata\x12\x1a.payload.v1.Upsert.Request\x1a!.payload.v1.Object.StreamLocation\"\x00(\x010\x01\x12~\n" +
	"\x17MultiUpsertWithMetadata\x12\x1f.payload.v1.Upsert.MultiRequest\x1a\x1c.payload.v1.Object.Locations\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/upsert/multiple/metadataB]\n" +
	"\x1eorg.vdaas.vald.api.v1.metadataB\fValdMetadataP\x01Z+github.com/vdaas/vald/apis/grpc/v1/metadatab\x06proto3"

var file_v1_vald_meta_proto_goTypes = []any{
	(*payload.Search_Request)(nil),          // 0: payload.v1.Search.Request
	(*payload.Search_IDRequest)(nil),        // 1: payload.v1.Search.IDRequest
	(*payload.Search_MultiRequest)(nil),     // 2: payload.v1.Search.MultiRequest
	(*payload.Search_MultiIDRequest)(nil),   // 3: payload.v1.Search.MultiIDRequest
	(*payload.Insert_Request)(nil),          // 4: payload.v1.Insert.Request
	(*payload.Insert_MultiRequest)(nil),     // 5: payload.v1.Insert.MultiRequest
	(*payload.Object_VectorRequest)(nil),    // 6: payload.v1.Object.VectorRequest
	(*payload.Object_List_Request)(nil),     // 7: payload.v1.Object.List.Request
	(*payload.Remove_Request)(nil),          // 8: payload.v1.Remove.Request
	(*payload.Remove_TimestampRequest)(nil), // 9: payload.v1.Remove.TimestampRequest
	(*payload.Remove_MultiRequest)(nil),     // 10: payload.v1.Remove.MultiRequest
	(*payload.Update_Request)(nil),          // 11: payload.v1.Update.Request
	(*payload.Update_MultiRequest)(nil),     // 12: payload.v1.Update.MultiRequest
	(*payload.Update_TimestampRequest)(nil), // 13: payload.v1.Update.TimestampRequest
	(*payload.Upsert_Request)(nil),          // 14: payload.v1.Upsert.Request
	(*payload.Upsert_MultiRequest)(nil),     // 15: payload.v1.Upsert.MultiRequest
	(*payload.Search_Response)(nil),         // 16: payload.v1.Search.Response
	(*payload.Search_StreamResponse)(nil),   // 17: payload.v1.Search.StreamResponse
	(*payload.Search_Responses)(nil),        // 18: payload.v1.Search.Responses
	(*payload.Object_Location)(nil),         // 19: payload.v1.Object.Location
	(*payload.Object_StreamLocation)(nil),   // 20: payload.v1.Object.StreamLocation
	(*payload.Object_Locations)(nil),        // 21: payload.v1.Object.Locations
	(*payload.Object_Vector)(nil),           // 22: payload.v1.Object.Vector
	(*payload.Object_StreamVector)(nil),     // 23: payload.v1.Object.StreamVector
	(*payload.Object_List_Response)(nil),    // 24: payload.v1.Object.List.Response
}
var file_v1_vald_meta_proto_depIdxs = []int32{
	0,  // 0: meta.v1.SearchWithMetadata.SearchWithMetadata:input_type -> payload.v1.Search.Request
	1,  // 1: meta.v1.SearchWithMetadata.SearchByIDWithMetadata:input_type -> payload.v1.Search.IDRequest
	0,  // 2: meta.v1.SearchWithMetadata.StreamSearchWithMetadata:input_type -> payload.v1.Search.Request
	1,  // 3: meta.v1.SearchWithMetadata.StreamSearchByIDWithMetadata:input_type -> payload.v1.Search.IDRequest
	2,  // 4: meta.v1.SearchWithMetadata.MultiSearchWithMetadata:input_type -> payload.v1.Search.MultiRequest
	3,  // 5: meta.v1.SearchWithMetadata.MultiSearchByIDWithMetadata:input_type -> payload.v1.Search.MultiIDRequest
	0,  // 6: meta.v1.SearchWithMetadata.LinearSearchWithMetadata:input_type -> payload.v1.Search.Request
	1,  // 7: meta.v1.SearchWithMetadata.LinearSearchByIDWithMetadata:input_type -> payload.v1.Search.IDRequest
	0,  // 8: meta.v1.SearchWithMetadata.StreamLinearSearchWithMetadata:input_type -> payload.v1.Search.Request
	1,  // 9: meta.v1.SearchWithMetadata.StreamLinearSearchByIDWithMetadata:input_type -> payload.v1.Search.IDRequest
	2,  // 10: meta.v1.SearchWithMetadata.MultiLinearSearchWithMetadata:input_type -> payload.v1.Search.MultiRequest
	3,  // 11: meta.v1.SearchWithMetadata.MultiLinearSearchByIDWithMetadata:input_type -> payload.v1.Search.MultiIDRequest
	4,  // 12: meta.v1.InsertWithMetadata.InsertWithMetadata:input_type -> payload.v1.Insert.Request
	4,  // 13: meta.v1.InsertWithMetadata.StreamInsertWithMetadata:input_type -> payload.v1.Insert.Request
	5,  // 14: meta.v1.InsertWithMetadata.MultiInsertWithMetadata:input_type -> payload.v1.Insert.MultiRequest
	6,  // 15: meta.v1.ObjectWithMetadata.GetObjectWithMetadata:input_type -> payload.v1.Object.VectorRequest
	6,  // 16: meta.v1.ObjectWithMetadata.StreamGetObjectWithMetadata:input_type -> payload.v1.Object.VectorRequest
	7,  // 17: meta.v1.ObjectWithMetadata.StreamListObjectWithMetadata:input_type -> payload.v1.Object.List.Request
	8,  // 18: meta.v1.RemoveWithMetadata.RemoveWithMetadata:input_type -> payload.v1.Remove.Request
	9,  // 19: meta.v1.RemoveWithMetadata.RemoveByTimestampWithMetadata:input_type -> payload.v1.Remove.TimestampRequest
	8,  // 20: meta.v1.RemoveWithMetadata.StreamRemoveWithMetadata:input_type -> payload.v1.Remove.Request
	10, // 21: meta.v1.RemoveWithMetadata.MultiRemoveWithMetadata:input_type -> payload.v1.Remove.MultiRequest
	11, // 22: meta.v1.UpdateWithMetadata.UpdateWithMetadata:input_type -> payload.v1.Update.Request
	11, // 23: meta.v1.UpdateWithMetadata.StreamUpdateWithMetadata:input_type -> payload.v1.Update.Request
	12, // 24: meta.v1.UpdateWithMetadata.MultiUpdateWithMetadata:input_type -> payload.v1.Update.MultiRequest
	13, // 25: meta.v1.UpdateWithMetadata.UpdateTimestampWithMetadata:input_type -> payload.v1.Update.TimestampRequest
	14, // 26: meta.v1.UpsertWithMetadata.UpsertWithMetadata:input_type -> payload.v1.Upsert.Request
	14, // 27: meta.v1.UpsertWithMetadata.StreamUpsertWithMetadata:input_type -> payload.v1.Upsert.Request
	15, // 28: meta.v1.UpsertWithMetadata.MultiUpsertWithMetadata:input_type -> payload.v1.Upsert.MultiRequest
	16, // 29: meta.v1.SearchWithMetadata.SearchWithMetadata:output_type -> payload.v1.Search.Response
	16, // 30: meta.v1.SearchWithMetadata.SearchByIDWithMetadata:output_type -> payload.v1.Search.Response
	17, // 31: meta.v1.SearchWithMetadata.StreamSearchWithMetadata:output_type -> payload.v1.Search.StreamResponse
	17, // 32: meta.v1.SearchWithMetadata.StreamSearchByIDWithMetadata:output_type -> payload.v1.Search.StreamResponse
	18, // 33: meta.v1.SearchWithMetadata.MultiSearchWithMetadata:output_type -> payload.v1.Search.Responses
	18, // 34: meta.v1.SearchWithMetadata.MultiSearchByIDWithMetadata:output_type -> payload.v1.Search.Responses
	16, // 35: meta.v1.SearchWithMetadata.LinearSearchWithMetadata:output_type -> payload.v1.Search.Response
	16, // 36: meta.v1.SearchWithMetadata.LinearSearchByIDWithMetadata:output_type -> payload.v1.Search.Response
	17, // 37: meta.v1.SearchWithMetadata.StreamLinearSearchWithMetadata:output_type -> payload.v1.Search.StreamResponse
	17, // 38: meta.v1.SearchWithMetadata.StreamLinearSearchByIDWithMetadata:output_type -> payload.v1.Search.StreamResponse
	18, // 39: meta.v1.SearchWithMetadata.MultiLinearSearchWithMetadata:output_type -> payload.v1.Search.Responses
	18, // 40: meta.v1.SearchWithMetadata.MultiLinearSearchByIDWithMetadata:output_type -> payload.v1.Search.Responses
	19, // 41: meta.v1.InsertWithMetadata.InsertWithMetadata:output_type -> payload.v1.Object.Location
	20, // 42: meta.v1.InsertWithMetadata.StreamInsertWithMetadata:output_type -> payload.v1.Object.StreamLocation
	21, // 43: meta.v1.InsertWithMetadata.MultiInsertWithMetadata:output_type -> payload.v1.Object.Locations
	22, // 44: meta.v1.ObjectWithMetadata.GetObjectWithMetadata:output_type -> payload.v1.Object.Vector
	23, // 45: meta.v1.ObjectWithMetadata.StreamGetObjectWithMetadata:output_type -> payload.v1.Object.StreamVector
	24, // 46: meta.v1.ObjectWithMetadata.StreamListObjectWithMetadata:output_type -> payload.v1.Object.List.Response
	19, // 47: meta.v1.RemoveWithMetadata.RemoveWithMetadata:output_type -> payload.v1.Object.Location
	21, // 48: meta.v1.RemoveWithMetadata.RemoveByTimestampWithMetadata:output_type -> payload.v1.Object.Locations
	20, // 49: meta.v1.RemoveWithMetadata.StreamRemoveWithMetadata:output_type -> payload.v1.Object.StreamLocation
	21, // 50: meta.v1.RemoveWithMetadata.MultiRemoveWithMetadata:output_type -> payload.v1.Object.Locations
	19, // 51: meta.v1.UpdateWithMetadata.UpdateWithMetadata:output_type -> payload.v1.Object.Location
	20, // 52: meta.v1.UpdateWithMetadata.StreamUpdateWithMetadata:output_type -> payload.v1.Object.StreamLocation
	21, // 53: meta.v1.UpdateWithMetadata.MultiUpdateWithMetadata:output_type -> payload.v1.Object.Locations
	19, // 54: meta.v1.UpdateWithMetadata.UpdateTimestampWithMetadata:output_type -> payload.v1.Object.Location
	19, // 55: meta.v1.UpsertWithMetadata.UpsertWithMetadata:output_type -> payload.v1.Object.Location
	20, // 56: meta.v1.UpsertWithMetadata.StreamUpsertWithMetadata:output_type -> payload.v1.Object.StreamLocation
	21, // 57: meta.v1.UpsertWithMetadata.MultiUpsertWithMetadata:output_type -> payload.v1.Object.Locations
	29, // [29:58] is the sub-list for method output_type
	0,  // [0:29] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_v1_vald_meta_proto_init() }
func file_v1_vald_meta_proto_init() {
	if File_v1_vald_meta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_vald_meta_proto_rawDesc), len(file_v1_vald_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_v1_vald_meta_proto_goTypes,
		DependencyIndexes: file_v1_vald_meta_proto_depIdxs,
	}.Build()
	File_v1_vald_meta_proto = out.File
	file_v1_vald_meta_proto_goTypes = nil
	file_v1_vald_meta_proto_depIdxs = nil
}
