---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vald.vdaas.org
  resources:
  - mvaldreleases
  - valdreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vald.vdaas.org
  resources:
  - mvaldreleases/finalizers
  - valdreleases/finalizers
  verbs:
  - update
- apiGroups:
  - vald.vdaas.org
  resources:
  - mvaldreleases/status
  - valdreleases/status
  verbs:
  - get
  - patch
  - update
