// Copyright (C) 2019-2026 vdaas.org vald team <vald@vdaas.org>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package service manages the main logic of server.
package service

import (
	"cmp"
	"context"
	"slices"
	"strconv"
	"testing"

	"github.com/vdaas/vald/apis/grpc/v1/payload"
	"github.com/vdaas/vald/internal/sync"
	"github.com/vdaas/vald/internal/sync/errgroup"
)

// app0Name is the first application group generated by newTickDiscoverer.
const app0Name = "app-0"

func assertSortedPods(tb testing.TB, what string, pods []*payload.Info_Pod) {
	tb.Helper()
	if !slices.IsSortedFunc(pods, byMemoryUsage) {
		tb.Errorf("%s is not sorted by ascending memory usage", what)
	}
}

// newTickDiscoverer builds a discoverer whose reconciled watch state (d.nodes,
// d.pods, d.nodeMetrics, d.podMetrics) is populated directly so that
// refreshSnapshots can be driven without a running controller. Every pod gets
// a deterministic memory usage > 0 so the maxPods nil padding in the node
// aggregates always sorts first. maxPods mirrors podEntries: the largest
// per-application group.
func newTickDiscoverer(tb testing.TB, nodes, namespaces, apps, podsPerApp int) (*discoverer, int) {
	tb.Helper()
	d := &discoverer{}
	d.maxPods.Store(int64(podsPerApp))
	d.eg, _ = errgroup.New(context.Background())
	nodeNames := make([]string, nodes)
	for i := range nodeNames {
		name := "node-" + strconv.Itoa(i)
		nodeNames[i] = name
		d.nodes.Store(name, &Node{
			Name:         name,
			InternalAddr: "10.0.0." + strconv.Itoa(i),
			CPUCapacity:  32,
			CPURemain:    16,
			MemCapacity:  64 << 30,
			MemRemain:    32 << 30,
		})
		d.nodeMetrics.Store(name, NodeMetrics{Name: name, CPU: float64(i + 1), Mem: float64((i + 1) * 100)})
	}
	total := 0
	for a := range apps {
		app := "app-" + strconv.Itoa(a)
		pods := make([]Pod, 0, podsPerApp)
		for i := range podsPerApp {
			name := app + "-" + strconv.Itoa(i)
			pods = append(pods, Pod{
				Name:       name,
				NodeName:   nodeNames[(a+i*7)%len(nodeNames)],
				Namespace:  "ns-" + strconv.Itoa(i%namespaces),
				IP:         "192.168.1." + strconv.Itoa(i),
				CPULimit:   4,
				CPURequest: 2,
				MemLimit:   8 << 30,
				MemRequest: 4 << 30,
			})
			d.podMetrics.Store(name, PodMetrics{
				Name:      name,
				Namespace: pods[i].Namespace,
				CPU:       float64((a+i*31)%17 + 1),
				Mem:       float64((a*podsPerApp+i*7919)%997 + 1),
			})
			total++
		}
		d.pods.Store(app, &pods)
	}
	return d, total
}

func TestDiscovererRefreshSnapshotsPublishesSortedSnapshots(t *testing.T) {
	t.Parallel()

	const (
		nodes      = 4
		namespaces = 2
		apps       = 3
		podsPerApp = 8
	)
	d, total := newTickDiscoverer(t, nodes, namespaces, apps, podsPerApp)
	d.refreshSnapshots(context.Background())

	pbName := *d.podsByName.Load()
	if len(pbName) != apps {
		t.Fatalf("podsByName groups = %d, want %d", len(pbName), apps)
	}
	seen := 0
	for app, pods := range pbName {
		if len(pods) != podsPerApp {
			t.Errorf("podsByName[%s] = %d pods, want %d", app, len(pods), podsPerApp)
		}
		seen += len(pods)
		assertSortedPods(t, "podsByName["+app+"]", pods)
	}
	if seen != total {
		t.Errorf("podsByName total = %d pods, want %d", seen, total)
	}

	seen = 0
	for ns, byApp := range *d.podsByNamespace.Load() {
		for app, pods := range byApp {
			seen += len(pods)
			assertSortedPods(t, "podsByNamespace["+ns+"]["+app+"]", pods)
		}
	}
	if seen != total {
		t.Errorf("podsByNamespace total = %d pods, want %d", seen, total)
	}

	pbNode := *d.podsByNode.Load()
	onNode := make(map[string]int, nodes)
	seen = 0
	for nodeName, byNs := range pbNode {
		for ns, byApp := range byNs {
			for app, pods := range byApp {
				seen += len(pods)
				onNode[nodeName] += len(pods)
				assertSortedPods(t, "podsByNode["+nodeName+"]["+ns+"]["+app+"]", pods)
				for _, pi := range pods {
					if pi.GetNode() == nil || pi.GetNode().GetName() != nodeName {
						t.Errorf("pod %s in podsByNode[%s] references node %q", pi.GetName(), nodeName, pi.GetNode().GetName())
					}
				}
			}
		}
	}
	if seen != total {
		t.Errorf("podsByNode total = %d pods, want %d", seen, total)
	}

	nbn := *d.nodeByName.Load()
	if len(nbn) != nodes {
		t.Fatalf("nodeByName entries = %d, want %d", len(nbn), nodes)
	}
	mp := int(d.maxPods.Load())
	for nodeName, n := range nbn {
		got := n.GetPods().GetPods()
		if want := mp + onNode[nodeName]; len(got) != want {
			t.Errorf("nodeByName[%s] aggregate = %d entries, want %d (maxPods padding + node pods)", nodeName, len(got), want)
			continue
		}
		for i := range mp {
			if got[i] != nil {
				t.Errorf("nodeByName[%s] aggregate[%d] = %v, want nil padding sorted first", nodeName, i, got[i])
				break
			}
		}
		rest := got[mp:]
		assertSortedPods(t, "nodeByName["+nodeName+"] aggregate", rest)
		for i, pi := range rest {
			if pi == nil {
				t.Errorf("nodeByName[%s] aggregate pod slot %d is nil", nodeName, i)
			}
		}
	}

	// Field mapping contract for a representative pod: app-0-0 lands on
	// node-0 / ns-0 with CPU usage 1 and memory usage 1 by fixture.
	var pi *payload.Info_Pod
	for _, p := range pbName[app0Name] {
		if p.GetName() == "app-0-0" {
			pi = p
			break
		}
	}
	if pi == nil {
		t.Fatal("pod app-0-0 not found in podsByName[app-0]")
	}
	if pi.GetAppName() != app0Name || pi.GetNamespace() != "ns-0" || pi.GetIp() != "192.168.1.0" {
		t.Errorf("pod identity = (%s, %s, %s), want (app-0, ns-0, 192.168.1.0)",
			pi.GetAppName(), pi.GetNamespace(), pi.GetIp())
	}
	if pi.GetCpu().GetLimit() != 4 || pi.GetCpu().GetRequest() != 2 || pi.GetCpu().GetUsage() != 1 {
		t.Errorf("pod cpu = %+v, want limit 4 / request 2 / usage 1", pi.GetCpu())
	}
	if pi.GetMemory().GetLimit() != 8<<30 || pi.GetMemory().GetRequest() != 4<<30 || pi.GetMemory().GetUsage() != 1 {
		t.Errorf("pod memory = %+v, want limit 8Gi / request 4Gi / usage 1", pi.GetMemory())
	}
	if pi.GetNode() != nbn["node-0"] {
		t.Errorf("pod node = %p, want the shared nodeByName[node-0] instance %p", pi.GetNode(), nbn["node-0"])
	}
}

func TestDiscovererRefreshSnapshotsSynthesizesUnknownNode(t *testing.T) {
	t.Parallel()

	d := &discoverer{}
	d.maxPods.Store(2)
	d.eg, _ = errgroup.New(context.Background())
	pods := make([]Pod, 0, 2)
	for i := range 2 {
		name := "a-" + strconv.Itoa(i)
		pods = append(pods, Pod{Name: name, NodeName: "ghost", Namespace: "ns"})
		d.podMetrics.Store(name, PodMetrics{Name: name, Namespace: "ns", Mem: float64(2 - i)})
	}
	d.pods.Store("a", &pods)

	d.refreshSnapshots(context.Background())

	ghost := (*d.nodeByName.Load())["ghost"]
	if ghost == nil {
		t.Fatal("nodeByName[ghost] placeholder was not synthesized")
	}
	got := ghost.GetPods().GetPods()
	if len(got) != 2 || got[0] == nil || got[1] == nil {
		t.Fatalf("ghost aggregate = %v, want 2 pods without nil padding", got)
	}
	if got[0].GetName() != "a-1" || got[1].GetName() != "a-0" {
		t.Errorf("ghost aggregate order = [%s, %s], want [a-1, a-0]", got[0].GetName(), got[1].GetName())
	}
	for _, pi := range (*d.podsByName.Load())["a"] {
		if pi.GetNode() != nil {
			t.Errorf("pod %s on unknown node carries node %v, want nil", pi.GetName(), pi.GetNode())
		}
	}
}

// TestDiscovererRefreshSnapshotsGroupSlicesAreIndependent proves the three
// snapshot maps never share a backing array: all four pods land in the same
// (node, namespace, app) group, so if the maps aliased one slice, reversing
// one would reorder the others. The concurrent per-map sorts inside
// refreshSnapshots rely on this independence to be race-free.
func TestDiscovererRefreshSnapshotsGroupSlicesAreIndependent(t *testing.T) {
	t.Parallel()

	d := &discoverer{}
	d.maxPods.Store(4)
	d.eg, _ = errgroup.New(context.Background())
	d.nodes.Store("n", &Node{Name: "n"})
	pods := make([]Pod, 0, 4)
	for i := range 4 {
		name := "a-" + strconv.Itoa(i)
		pods = append(pods, Pod{Name: name, NodeName: "n", Namespace: "ns"})
		d.podMetrics.Store(name, PodMetrics{Name: name, Namespace: "ns", Mem: float64(4 - i)})
	}
	d.pods.Store("a", &pods)

	d.refreshSnapshots(context.Background())

	byName := (*d.podsByName.Load())["a"]
	byNamespace := (*d.podsByNamespace.Load())["ns"]["a"]
	byNode := (*d.podsByNode.Load())["n"]["ns"]["a"]
	if len(byName) != 4 || len(byNamespace) != 4 || len(byNode) != 4 {
		t.Fatalf("group lengths = (%d, %d, %d), want (4, 4, 4)", len(byName), len(byNamespace), len(byNode))
	}

	slices.Reverse(byName)
	if slices.IsSortedFunc(byName, byMemoryUsage) {
		t.Fatal("fixture must use distinct usages so a reversed group is unsorted")
	}
	assertSortedPods(t, "podsByNamespace group after reversing podsByName", byNamespace)
	assertSortedPods(t, "podsByNode group after reversing podsByName", byNode)

	slices.Reverse(byNamespace)
	assertSortedPods(t, "podsByNode group after reversing podsByNamespace", byNode)
}

// TestDiscovererRefreshSnapshotsRaceStress drives the tick at cluster scale
// (50 nodes / 1000 pods) so that, under -race, the three concurrent
// per-snapshot sorters would be flagged if the maps ever shared a backing
// array.
func TestDiscovererRefreshSnapshotsRaceStress(t *testing.T) {
	t.Parallel()

	d, total := newTickDiscoverer(t, 50, 2, 10, 100)
	ctx := context.Background()
	for range 5 {
		d.refreshSnapshots(ctx)
	}
	seen := 0
	for app, pods := range *d.podsByName.Load() {
		seen += len(pods)
		assertSortedPods(t, "podsByName["+app+"]", pods)
	}
	if seen != total {
		t.Errorf("published pods = %d, want %d", seen, total)
	}
}

// TestDiscovererGetPodsResponse pins the GetPods response contract: pods are
// ordered by ascending memory usage, every pod carries its node with the
// recursive per-node pod aggregate stripped, and the same request against the
// same snapshot reproduces the same content.
func TestDiscovererGetPodsResponse(t *testing.T) {
	t.Parallel()

	const (
		nodes      = 4
		namespaces = 2
		apps       = 3
		podsPerApp = 8
	)
	d, total := newTickDiscoverer(t, nodes, namespaces, apps, podsPerApp)
	d.refreshSnapshots(context.Background())

	all := &payload.Discoverer_Request{Node: "*", Namespace: "*", Name: "*"}
	pods, err := d.GetPods(all)
	if err != nil {
		t.Fatal(err)
	}
	if len(pods.GetPods()) != total {
		t.Fatalf("GetPods(*) = %d pods, want %d", len(pods.GetPods()), total)
	}
	assertSortedPods(t, "GetPods(*) response", pods.GetPods())
	for _, pi := range pods.GetPods() {
		if pi.GetNode() == nil {
			t.Errorf("response pod %s has no node", pi.GetName())
			continue
		}
		if pi.GetNode().GetPods() != nil {
			t.Errorf("response pod %s node %s still nests the recursive pod aggregate", pi.GetName(), pi.GetNode().GetName())
		}
	}

	again, err := d.GetPods(all)
	if err != nil {
		t.Fatal(err)
	}
	if len(again.GetPods()) != len(pods.GetPods()) {
		t.Fatalf("second GetPods(*) = %d pods, want %d", len(again.GetPods()), len(pods.GetPods()))
	}
	for i, pi := range pods.GetPods() {
		if got := again.GetPods()[i]; got.GetName() != pi.GetName() {
			t.Errorf("second GetPods(*) pod[%d] = %s, want %s (identical order/content)", i, got.GetName(), pi.GetName())
		}
	}

	byName, err := d.GetPods(&payload.Discoverer_Request{Name: app0Name})
	if err != nil {
		t.Fatal(err)
	}
	if len(byName.GetPods()) != podsPerApp {
		t.Fatalf("GetPods(app-0) = %d pods, want %d", len(byName.GetPods()), podsPerApp)
	}
	assertSortedPods(t, "GetPods(app-0) response", byName.GetPods())
	for _, pi := range byName.GetPods() {
		if pi.GetAppName() != app0Name {
			t.Errorf("GetPods(app-0) returned pod %s of app %s", pi.GetName(), pi.GetAppName())
		}
	}
}

// TestDiscovererGetNodesResponse pins the GetNodes response contract: nodes
// are ordered by ascending memory usage, every node nests its own sorted pod
// aggregate, and the nested pods never link back to a node (the previous
// in-place implementation left the single-node response cyclic:
// node.Pods.Pods[i].Node == node, which is unmarshalable).
func TestDiscovererGetNodesResponse(t *testing.T) {
	t.Parallel()

	const (
		nodes      = 4
		namespaces = 2
		apps       = 3
		podsPerApp = 8
	)
	d, total := newTickDiscoverer(t, nodes, namespaces, apps, podsPerApp)
	d.refreshSnapshots(context.Background())

	resp, err := d.GetNodes(&payload.Discoverer_Request{Node: "*", Namespace: "*", Name: "*"})
	if err != nil {
		t.Fatal(err)
	}
	if len(resp.GetNodes()) != nodes {
		t.Fatalf("GetNodes(*) = %d nodes, want %d", len(resp.GetNodes()), nodes)
	}
	if !slices.IsSortedFunc(resp.GetNodes(), func(left, right *payload.Info_Node) int {
		return cmp.Compare(left.GetMemory().GetUsage(), right.GetMemory().GetUsage())
	}) {
		t.Error("GetNodes(*) response is not sorted by ascending node memory usage")
	}
	nbn := *d.nodeByName.Load()
	seen := 0
	for _, n := range resp.GetNodes() {
		shared, ok := nbn[n.GetName()]
		if !ok {
			t.Errorf("GetNodes(*) returned unknown node %s", n.GetName())
			continue
		}
		if n.GetInternalAddr() != shared.GetInternalAddr() ||
			n.GetCpu().GetUsage() != shared.GetCpu().GetUsage() ||
			n.GetMemory().GetUsage() != shared.GetMemory().GetUsage() {
			t.Errorf("GetNodes(*) node %s fields diverge from the snapshot", n.GetName())
		}
		if n.GetPods() == nil {
			t.Errorf("GetNodes(*) node %s has no pod aggregate", n.GetName())
			continue
		}
		assertSortedPods(t, "GetNodes(*) node "+n.GetName()+" pods", n.GetPods().GetPods())
		for _, pi := range n.GetPods().GetPods() {
			if pi.GetNode() != nil {
				t.Errorf("GetNodes(*) pod %s under node %s still links a node", pi.GetName(), n.GetName())
			}
		}
		seen += len(n.GetPods().GetPods())
	}
	if seen != total {
		t.Errorf("GetNodes(*) total nested pods = %d, want %d", seen, total)
	}

	one, err := d.GetNodes(&payload.Discoverer_Request{Node: "node-0"})
	if err != nil {
		t.Fatal(err)
	}
	if len(one.GetNodes()) != 1 || one.GetNodes()[0].GetName() != "node-0" {
		t.Fatalf("GetNodes(node-0) = %v, want exactly node-0", one.GetNodes())
	}
	n := one.GetNodes()[0]
	if n.GetPods() == nil || len(n.GetPods().GetPods()) == 0 {
		t.Fatal("GetNodes(node-0) has no nested pods")
	}
	assertSortedPods(t, "GetNodes(node-0) pods", n.GetPods().GetPods())
	for _, pi := range n.GetPods().GetPods() {
		if pi.GetNode() != nil {
			t.Errorf("GetNodes(node-0) pod %s links node %p (cyclic response)", pi.GetName(), pi.GetNode())
		}
	}
}

// TestDiscovererReadHandlersDoNotMutateSharedSnapshot drives concurrent
// GetPods and GetNodes against one published snapshot. Read handlers must
// treat the snapshot as immutable: under -race any in-place recursion
// stripping (pod.Node.Pods = nil / node.Pods = resp) is flagged as a data
// race between requests, and the post-conditions below fail even without
// -race if a handler rewired the shared nodes or pods.
func TestDiscovererReadHandlersDoNotMutateSharedSnapshot(t *testing.T) {
	t.Parallel()

	const (
		nodes      = 4
		namespaces = 2
		apps       = 3
		podsPerApp = 8
		workers    = 4
		iterations = 100
	)
	d, total := newTickDiscoverer(t, nodes, namespaces, apps, podsPerApp)
	d.refreshSnapshots(context.Background())

	nbn := *d.nodeByName.Load()
	wantAggregate := make(map[string]int, len(nbn))
	for name, n := range nbn {
		wantAggregate[name] = len(n.GetPods().GetPods())
	}

	var wg sync.WaitGroup
	for range workers {
		wg.Add(2)
		go func() {
			defer wg.Done()
			for range iterations {
				pods, err := d.GetPods(&payload.Discoverer_Request{Node: "*", Namespace: "*", Name: "*"})
				if err != nil {
					t.Error(err)
					return
				}
				if len(pods.GetPods()) != total {
					t.Errorf("GetPods returned %d pods, want %d", len(pods.GetPods()), total)
					return
				}
			}
		}()
		go func() {
			defer wg.Done()
			for range iterations {
				resp, err := d.GetNodes(&payload.Discoverer_Request{Node: "*", Namespace: "*", Name: "*"})
				if err != nil {
					t.Error(err)
					return
				}
				if len(resp.GetNodes()) != nodes {
					t.Errorf("GetNodes returned %d nodes, want %d", len(resp.GetNodes()), nodes)
					return
				}
			}
		}()
	}
	wg.Wait()

	// The published snapshot must be exactly as the tick left it.
	for name, n := range nbn {
		if got := len(n.GetPods().GetPods()); got != wantAggregate[name] {
			t.Errorf("shared nodeByName[%s] aggregate = %d entries after reads, want %d untouched", name, got, wantAggregate[name])
		}
	}
	for app, pods := range *d.podsByName.Load() {
		assertSortedPods(t, "shared podsByName["+app+"] after reads", pods)
		for _, pi := range pods {
			if pi.GetNode() == nil {
				t.Errorf("shared pod %s in podsByName[%s] lost its node link after reads", pi.GetName(), app)
			} else if pi.GetNode().GetPods() == nil {
				t.Errorf("shared node %s lost its pod aggregate after reads (via pod %s)", pi.GetNode().GetName(), pi.GetName())
			}
		}
	}
}

// TestDiscovererReadResponsesDetachedFromSnapshot ensures responses are
// caller-owned: they never alias the shared group slices or the shared
// pod/node messages, so mutating a response leaves the snapshot intact.
func TestDiscovererReadResponsesDetachedFromSnapshot(t *testing.T) {
	t.Parallel()

	d, _ := newTickDiscoverer(t, 2, 1, 1, 4)
	d.refreshSnapshots(context.Background())

	resp, err := d.GetPods(&payload.Discoverer_Request{Name: app0Name})
	if err != nil {
		t.Fatal(err)
	}
	shared := (*d.podsByName.Load())[app0Name]
	if len(resp.GetPods()) != len(shared) {
		t.Fatalf("GetPods(app-0) = %d pods, want %d", len(resp.GetPods()), len(shared))
	}
	if &resp.GetPods()[0] == &shared[0] {
		t.Error("GetPods response aliases the shared snapshot group slice")
	}
	nbn := *d.nodeByName.Load()
	for i, pi := range resp.GetPods() {
		if pi == shared[i] {
			t.Errorf("GetPods response pod %s is the shared snapshot message", pi.GetName())
		}
		if pi.GetNode() != nil && pi.GetNode() == nbn[pi.GetNode().GetName()] {
			t.Errorf("GetPods response pod %s links the shared snapshot node %s", pi.GetName(), pi.GetNode().GetName())
		}
	}
	for _, pi := range resp.GetPods() {
		pi.Node = nil
	}
	for _, pi := range shared {
		if pi.GetNode() == nil {
			t.Errorf("mutating the GetPods response cleared the shared pod %s node link", pi.GetName())
		}
	}

	nresp, err := d.GetNodes(&payload.Discoverer_Request{Node: "*", Namespace: "*", Name: "*"})
	if err != nil {
		t.Fatal(err)
	}
	for _, n := range nresp.GetNodes() {
		if n == nbn[n.GetName()] {
			t.Errorf("GetNodes response node %s is the shared snapshot message", n.GetName())
		}
		n.Pods = nil
	}
	for name, n := range nbn {
		if n.GetPods() == nil || len(n.GetPods().GetPods()) == 0 {
			t.Errorf("mutating the GetNodes response cleared the shared node %s aggregate", name)
		}
	}
}

func BenchmarkDiscovererRefreshSnapshots(b *testing.B) {
	d, _ := newTickDiscoverer(b, 50, 2, 10, 100) // 50 nodes / 2 namespaces / 10 apps / 1000 pods
	ctx := context.Background()
	b.ReportAllocs()
	for b.Loop() {
		d.refreshSnapshots(ctx)
	}
}

// TestDiscovererGetNodesEmptyAggregateShape pins the response shape for a
// node that carries no pods in the snapshot: GetPods returns node-not-found
// for it, and the response must keep an empty, non-nil pod aggregate
// (mirroring the pre-copy response shape).
func TestDiscovererGetNodesEmptyAggregateShape(t *testing.T) {
	t.Parallel()

	d, _ := newTickDiscoverer(t, 2, 1, 1, 1) // 2 nodes, 1 pod -> one node stays empty
	d.refreshSnapshots(context.Background())

	nodes, err := d.GetNodes(&payload.Discoverer_Request{Node: "*"})
	if err != nil {
		t.Fatalf("GetNodes() error = %v, want nil", err)
	}
	var emptySeen bool
	for _, n := range nodes.GetNodes() {
		if n.GetPods() == nil {
			t.Fatalf("node %s aggregate = nil, want empty non-nil", n.GetName())
		}
		if len(n.GetPods().GetPods()) == 0 {
			emptySeen = true
		}
	}
	if !emptySeen {
		t.Fatal("fixture produced no empty node; the empty-aggregate path was not exercised")
	}
}

func BenchmarkDiscovererGetPods(b *testing.B) {
	d, total := newTickDiscoverer(b, 50, 2, 10, 100)
	d.refreshSnapshots(context.Background())
	req := &payload.Discoverer_Request{Node: "*", Namespace: "*", Name: "*"}
	b.ReportAllocs()
	for b.Loop() {
		pods, err := d.GetPods(req)
		if err != nil || len(pods.GetPods()) != total {
			b.Fatalf("GetPods = %d pods, err %v", len(pods.GetPods()), err)
		}
	}
}

func BenchmarkDiscovererGetNodes(b *testing.B) {
	d, _ := newTickDiscoverer(b, 50, 2, 10, 100)
	d.refreshSnapshots(context.Background())
	req := new(payload.Discoverer_Request)
	b.ReportAllocs()
	for b.Loop() {
		req.Node = "*" // GetNodes rewrites req.Node while iterating nodes
		nodes, err := d.GetNodes(req)
		if err != nil || len(nodes.GetNodes()) != 50 {
			b.Fatalf("GetNodes = %d nodes, err %v", len(nodes.GetNodes()), err)
		}
	}
}

// NOT IMPLEMENTED BELOW
//
// func TestNew(t *testing.T) {
// 	type args struct {
// 		selector *config.Selectors
// 		opts     []Option
// 	}
// 	type want struct {
// 		want Discoverer
// 		err  error
// 	}
// 	type test struct {
// 		name       string
// 		args       args
// 		want       want
// 		checkFunc  func(want, Discoverer, error) error
// 		beforeFunc func(*testing.T, args)
// 		afterFunc  func(*testing.T, args)
// 	}
// 	defaultCheckFunc := func(w want, got Discoverer, err error) error {
// 		if !errors.Is(err, w.err) {
// 			return errors.Errorf("got_error: \"%#v\",\n\t\t\t\twant: \"%#v\"", err, w.err)
// 		}
// 		if !reflect.DeepEqual(got, w.want) {
// 			return errors.Errorf("got: \"%#v\",\n\t\t\t\twant: \"%#v\"", got, w.want)
// 		}
// 		return nil
// 	}
// 	tests := []test{
// 		// TODO test cases
// 		/*
// 		   {
// 		       name: "test_case_1",
// 		       args: args {
// 		           selector:nil,
// 		           opts:nil,
// 		       },
// 		       want: want{},
// 		       checkFunc: defaultCheckFunc,
// 		       beforeFunc: func(t *testing.T, args args) {
// 		           t.Helper()
// 		       },
// 		       afterFunc: func(t *testing.T, args args) {
// 		           t.Helper()
// 		       },
// 		   },
// 		*/
//
// 		// TODO test cases
// 		/*
// 		   func() test {
// 		       return test {
// 		           name: "test_case_2",
// 		           args: args {
// 		           selector:nil,
// 		           opts:nil,
// 		           },
// 		           want: want{},
// 		           checkFunc: defaultCheckFunc,
// 		           beforeFunc: func(t *testing.T, args args) {
// 		               t.Helper()
// 		           },
// 		           afterFunc: func(t *testing.T, args args) {
// 		               t.Helper()
// 		           },
// 		       }
// 		   }(),
// 		*/
// 	}
//
// 	for _, tc := range tests {
// 		test := tc
// 		t.Run(test.name, func(tt *testing.T) {
// 			tt.Parallel()
// 			defer goleak.VerifyNone(tt, goleak.IgnoreCurrent())
// 			if test.beforeFunc != nil {
// 				test.beforeFunc(tt, test.args)
// 			}
// 			if test.afterFunc != nil {
// 				defer test.afterFunc(tt, test.args)
// 			}
// 			checkFunc := test.checkFunc
// 			if test.checkFunc == nil {
// 				checkFunc = defaultCheckFunc
// 			}
//
// 			got, err := New(test.args.selector, test.args.opts...)
// 			if err := checkFunc(test.want, got, err); err != nil {
// 				tt.Errorf("error = %v", err)
// 			}
// 		})
// 	}
// }
//
// func Test_discoverer_Start(t *testing.T) {
// 	type args struct {
// 		ctx context.Context
// 	}
// 	type fields struct {
// 		eg              errgroup.Group
// 		der             net.Dialer
// 		ctrl            k8s.Controller
// 		podsByName      atomic.Pointer[map[string][]*payload.Info_Pod]
// 		svcsByName      atomic.Pointer[map[string]*payload.Info_Service]
// 		nodeByName      atomic.Pointer[map[string]*payload.Info_Node]
// 		podsByNode      atomic.Pointer[map[string]map[string]map[string][]*payload.Info_Pod]
// 		podsByNamespace atomic.Pointer[map[string]map[string][]*payload.Info_Pod]
// 		namespace       string
// 		name            string
// 		pods            sync.Map[string, *[]Pod]
// 		nodeMetrics     sync.Map[string, NodeMetrics]
// 		nodes           sync.Map[string, *Node]
// 		podMetrics      sync.Map[string, PodMetrics]
// 		maxPods         int
// 		csd             time.Duration
// 	}
// 	type want struct {
// 		want <-chan error
// 		err  error
// 	}
// 	type test struct {
// 		name       string
// 		args       args
// 		fields     fields
// 		want       want
// 		checkFunc  func(want, <-chan error, error) error
// 		beforeFunc func(*testing.T, args)
// 		afterFunc  func(*testing.T, args)
// 	}
// 	defaultCheckFunc := func(w want, got <-chan error, err error) error {
// 		if !errors.Is(err, w.err) {
// 			return errors.Errorf("got_error: \"%#v\",\n\t\t\t\twant: \"%#v\"", err, w.err)
// 		}
// 		if !reflect.DeepEqual(got, w.want) {
// 			return errors.Errorf("got: \"%#v\",\n\t\t\t\twant: \"%#v\"", got, w.want)
// 		}
// 		return nil
// 	}
// 	tests := []test{
// 		// TODO test cases
// 		/*
// 		   {
// 		       name: "test_case_1",
// 		       args: args {
// 		           ctx:nil,
// 		       },
// 		       fields: fields {
// 		           eg:nil,
// 		           der:nil,
// 		           ctrl:nil,
// 		           podsByName:nil,
// 		           svcsByName:nil,
// 		           nodeByName:nil,
// 		           podsByNode:nil,
// 		           podsByNamespace:nil,
// 		           namespace:"",
// 		           name:"",
// 		           pods:nil,
// 		           nodeMetrics:nil,
// 		           nodes:nil,
// 		           podMetrics:nil,
// 		           maxPods:0,
// 		           csd:nil,
// 		       },
// 		       want: want{},
// 		       checkFunc: defaultCheckFunc,
// 		       beforeFunc: func(t *testing.T, args args) {
// 		           t.Helper()
// 		       },
// 		       afterFunc: func(t *testing.T, args args) {
// 		           t.Helper()
// 		       },
// 		   },
// 		*/
//
// 		// TODO test cases
// 		/*
// 		   func() test {
// 		       return test {
// 		           name: "test_case_2",
// 		           args: args {
// 		           ctx:nil,
// 		           },
// 		           fields: fields {
// 		           eg:nil,
// 		           der:nil,
// 		           ctrl:nil,
// 		           podsByName:nil,
// 		           svcsByName:nil,
// 		           nodeByName:nil,
// 		           podsByNode:nil,
// 		           podsByNamespace:nil,
// 		           namespace:"",
// 		           name:"",
// 		           pods:nil,
// 		           nodeMetrics:nil,
// 		           nodes:nil,
// 		           podMetrics:nil,
// 		           maxPods:0,
// 		           csd:nil,
// 		           },
// 		           want: want{},
// 		           checkFunc: defaultCheckFunc,
// 		           beforeFunc: func(t *testing.T, args args) {
// 		               t.Helper()
// 		           },
// 		           afterFunc: func(t *testing.T, args args) {
// 		               t.Helper()
// 		           },
// 		       }
// 		   }(),
// 		*/
// 	}
//
// 	for _, tc := range tests {
// 		test := tc
// 		t.Run(test.name, func(tt *testing.T) {
// 			tt.Parallel()
// 			defer goleak.VerifyNone(tt, goleak.IgnoreCurrent())
// 			if test.beforeFunc != nil {
// 				test.beforeFunc(tt, test.args)
// 			}
// 			if test.afterFunc != nil {
// 				defer test.afterFunc(tt, test.args)
// 			}
// 			checkFunc := test.checkFunc
// 			if test.checkFunc == nil {
// 				checkFunc = defaultCheckFunc
// 			}
// 			d := &discoverer{
// 				eg:              test.fields.eg,
// 				der:             test.fields.der,
// 				ctrl:            test.fields.ctrl,
// 				podsByName:      test.fields.podsByName,
// 				svcsByName:      test.fields.svcsByName,
// 				nodeByName:      test.fields.nodeByName,
// 				podsByNode:      test.fields.podsByNode,
// 				podsByNamespace: test.fields.podsByNamespace,
// 				namespace:       test.fields.namespace,
// 				name:            test.fields.name,
// 				pods:            test.fields.pods,
// 				nodeMetrics:     test.fields.nodeMetrics,
// 				nodes:           test.fields.nodes,
// 				podMetrics:      test.fields.podMetrics,
// 				maxPods:         test.fields.maxPods,
// 				csd:             test.fields.csd,
// 			}
//
// 			got, err := d.Start(test.args.ctx)
// 			if err := checkFunc(test.want, got, err); err != nil {
// 				tt.Errorf("error = %v", err)
// 			}
// 		})
// 	}
// }
//
// func Test_discoverer_refreshSnapshots(t *testing.T) {
// 	type args struct {
// 		ctx context.Context
// 	}
// 	type fields struct {
// 		eg              errgroup.Group
// 		der             net.Dialer
// 		ctrl            k8s.Controller
// 		podsByName      atomic.Pointer[map[string][]*payload.Info_Pod]
// 		svcsByName      atomic.Pointer[map[string]*payload.Info_Service]
// 		nodeByName      atomic.Pointer[map[string]*payload.Info_Node]
// 		podsByNode      atomic.Pointer[map[string]map[string]map[string][]*payload.Info_Pod]
// 		podsByNamespace atomic.Pointer[map[string]map[string][]*payload.Info_Pod]
// 		namespace       string
// 		name            string
// 		pods            sync.Map[string, *[]Pod]
// 		nodeMetrics     sync.Map[string, NodeMetrics]
// 		nodes           sync.Map[string, *Node]
// 		podMetrics      sync.Map[string, PodMetrics]
// 		maxPods         int
// 		csd             time.Duration
// 	}
// 	type want struct{}
// 	type test struct {
// 		name       string
// 		args       args
// 		fields     fields
// 		want       want
// 		checkFunc  func(want) error
// 		beforeFunc func(*testing.T, args)
// 		afterFunc  func(*testing.T, args)
// 	}
// 	defaultCheckFunc := func(w want) error {
// 		return nil
// 	}
// 	tests := []test{
// 		// TODO test cases
// 		/*
// 		   {
// 		       name: "test_case_1",
// 		       args: args {
// 		           ctx:nil,
// 		       },
// 		       fields: fields {
// 		           eg:nil,
// 		           der:nil,
// 		           ctrl:nil,
// 		           podsByName:nil,
// 		           svcsByName:nil,
// 		           nodeByName:nil,
// 		           podsByNode:nil,
// 		           podsByNamespace:nil,
// 		           namespace:"",
// 		           name:"",
// 		           pods:nil,
// 		           nodeMetrics:nil,
// 		           nodes:nil,
// 		           podMetrics:nil,
// 		           maxPods:0,
// 		           csd:nil,
// 		       },
// 		       want: want{},
// 		       checkFunc: defaultCheckFunc,
// 		       beforeFunc: func(t *testing.T, args args) {
// 		           t.Helper()
// 		       },
// 		       afterFunc: func(t *testing.T, args args) {
// 		           t.Helper()
// 		       },
// 		   },
// 		*/
//
// 		// TODO test cases
// 		/*
// 		   func() test {
// 		       return test {
// 		           name: "test_case_2",
// 		           args: args {
// 		           ctx:nil,
// 		           },
// 		           fields: fields {
// 		           eg:nil,
// 		           der:nil,
// 		           ctrl:nil,
// 		           podsByName:nil,
// 		           svcsByName:nil,
// 		           nodeByName:nil,
// 		           podsByNode:nil,
// 		           podsByNamespace:nil,
// 		           namespace:"",
// 		           name:"",
// 		           pods:nil,
// 		           nodeMetrics:nil,
// 		           nodes:nil,
// 		           podMetrics:nil,
// 		           maxPods:0,
// 		           csd:nil,
// 		           },
// 		           want: want{},
// 		           checkFunc: defaultCheckFunc,
// 		           beforeFunc: func(t *testing.T, args args) {
// 		               t.Helper()
// 		           },
// 		           afterFunc: func(t *testing.T, args args) {
// 		               t.Helper()
// 		           },
// 		       }
// 		   }(),
// 		*/
// 	}
//
// 	for _, tc := range tests {
// 		test := tc
// 		t.Run(test.name, func(tt *testing.T) {
// 			tt.Parallel()
// 			defer goleak.VerifyNone(tt, goleak.IgnoreCurrent())
// 			if test.beforeFunc != nil {
// 				test.beforeFunc(tt, test.args)
// 			}
// 			if test.afterFunc != nil {
// 				defer test.afterFunc(tt, test.args)
// 			}
// 			checkFunc := test.checkFunc
// 			if test.checkFunc == nil {
// 				checkFunc = defaultCheckFunc
// 			}
// 			d := &discoverer{
// 				eg:              test.fields.eg,
// 				der:             test.fields.der,
// 				ctrl:            test.fields.ctrl,
// 				podsByName:      test.fields.podsByName,
// 				svcsByName:      test.fields.svcsByName,
// 				nodeByName:      test.fields.nodeByName,
// 				podsByNode:      test.fields.podsByNode,
// 				podsByNamespace: test.fields.podsByNamespace,
// 				namespace:       test.fields.namespace,
// 				name:            test.fields.name,
// 				pods:            test.fields.pods,
// 				nodeMetrics:     test.fields.nodeMetrics,
// 				nodes:           test.fields.nodes,
// 				podMetrics:      test.fields.podMetrics,
// 				maxPods:         test.fields.maxPods,
// 				csd:             test.fields.csd,
// 			}
//
// 			d.refreshSnapshots(test.args.ctx)
// 			if err := checkFunc(test.want); err != nil {
// 				tt.Errorf("error = %v", err)
// 			}
// 		})
// 	}
// }
//
// func Test_byMemoryUsage(t *testing.T) {
// 	type args struct {
// 		left  *payload.Info_Pod
// 		right *payload.Info_Pod
// 	}
// 	type want struct {
// 		want int
// 	}
// 	type test struct {
// 		name       string
// 		args       args
// 		want       want
// 		checkFunc  func(want, int) error
// 		beforeFunc func(*testing.T, args)
// 		afterFunc  func(*testing.T, args)
// 	}
// 	defaultCheckFunc := func(w want, got int) error {
// 		if !reflect.DeepEqual(got, w.want) {
// 			return errors.Errorf("got: \"%#v\",\n\t\t\t\twant: \"%#v\"", got, w.want)
// 		}
// 		return nil
// 	}
// 	tests := []test{
// 		// TODO test cases
// 		/*
// 		   {
// 		       name: "test_case_1",
// 		       args: args {
// 		           left:nil,
// 		           right:nil,
// 		       },
// 		       want: want{},
// 		       checkFunc: defaultCheckFunc,
// 		       beforeFunc: func(t *testing.T, args args) {
// 		           t.Helper()
// 		       },
// 		       afterFunc: func(t *testing.T, args args) {
// 		           t.Helper()
// 		       },
// 		   },
// 		*/
//
// 		// TODO test cases
// 		/*
// 		   func() test {
// 		       return test {
// 		           name: "test_case_2",
// 		           args: args {
// 		           left:nil,
// 		           right:nil,
// 		           },
// 		           want: want{},
// 		           checkFunc: defaultCheckFunc,
// 		           beforeFunc: func(t *testing.T, args args) {
// 		               t.Helper()
// 		           },
// 		           afterFunc: func(t *testing.T, args args) {
// 		               t.Helper()
// 		           },
// 		       }
// 		   }(),
// 		*/
// 	}
//
// 	for _, tc := range tests {
// 		test := tc
// 		t.Run(test.name, func(tt *testing.T) {
// 			tt.Parallel()
// 			defer goleak.VerifyNone(tt, goleak.IgnoreCurrent())
// 			if test.beforeFunc != nil {
// 				test.beforeFunc(tt, test.args)
// 			}
// 			if test.afterFunc != nil {
// 				defer test.afterFunc(tt, test.args)
// 			}
// 			checkFunc := test.checkFunc
// 			if test.checkFunc == nil {
// 				checkFunc = defaultCheckFunc
// 			}
//
// 			got := byMemoryUsage(test.args.left, test.args.right)
// 			if err := checkFunc(test.want, got); err != nil {
// 				tt.Errorf("error = %v", err)
// 			}
// 		})
// 	}
// }
//
// func Test_responseNode(t *testing.T) {
// 	type args struct {
// 		n *payload.Info_Node
// 	}
// 	type want struct {
// 		want *payload.Info_Node
// 	}
// 	type test struct {
// 		name       string
// 		args       args
// 		want       want
// 		checkFunc  func(want, *payload.Info_Node) error
// 		beforeFunc func(*testing.T, args)
// 		afterFunc  func(*testing.T, args)
// 	}
// 	defaultCheckFunc := func(w want, got *payload.Info_Node) error {
// 		if !reflect.DeepEqual(got, w.want) {
// 			return errors.Errorf("got: \"%#v\",\n\t\t\t\twant: \"%#v\"", got, w.want)
// 		}
// 		return nil
// 	}
// 	tests := []test{
// 		// TODO test cases
// 		/*
// 		   {
// 		       name: "test_case_1",
// 		       args: args {
// 		           n:nil,
// 		       },
// 		       want: want{},
// 		       checkFunc: defaultCheckFunc,
// 		       beforeFunc: func(t *testing.T, args args) {
// 		           t.Helper()
// 		       },
// 		       afterFunc: func(t *testing.T, args args) {
// 		           t.Helper()
// 		       },
// 		   },
// 		*/
//
// 		// TODO test cases
// 		/*
// 		   func() test {
// 		       return test {
// 		           name: "test_case_2",
// 		           args: args {
// 		           n:nil,
// 		           },
// 		           want: want{},
// 		           checkFunc: defaultCheckFunc,
// 		           beforeFunc: func(t *testing.T, args args) {
// 		               t.Helper()
// 		           },
// 		           afterFunc: func(t *testing.T, args args) {
// 		               t.Helper()
// 		           },
// 		       }
// 		   }(),
// 		*/
// 	}
//
// 	for _, tc := range tests {
// 		test := tc
// 		t.Run(test.name, func(tt *testing.T) {
// 			tt.Parallel()
// 			defer goleak.VerifyNone(tt, goleak.IgnoreCurrent())
// 			if test.beforeFunc != nil {
// 				test.beforeFunc(tt, test.args)
// 			}
// 			if test.afterFunc != nil {
// 				defer test.afterFunc(tt, test.args)
// 			}
// 			checkFunc := test.checkFunc
// 			if test.checkFunc == nil {
// 				checkFunc = defaultCheckFunc
// 			}
//
// 			got := responseNode(test.args.n)
// 			if err := checkFunc(test.want, got); err != nil {
// 				tt.Errorf("error = %v", err)
// 			}
// 		})
// 	}
// }
//
// func Test_responsePod(t *testing.T) {
// 	type args struct {
// 		p *payload.Info_Pod
// 	}
// 	type want struct {
// 		want *payload.Info_Pod
// 	}
// 	type test struct {
// 		name       string
// 		args       args
// 		want       want
// 		checkFunc  func(want, *payload.Info_Pod) error
// 		beforeFunc func(*testing.T, args)
// 		afterFunc  func(*testing.T, args)
// 	}
// 	defaultCheckFunc := func(w want, got *payload.Info_Pod) error {
// 		if !reflect.DeepEqual(got, w.want) {
// 			return errors.Errorf("got: \"%#v\",\n\t\t\t\twant: \"%#v\"", got, w.want)
// 		}
// 		return nil
// 	}
// 	tests := []test{
// 		// TODO test cases
// 		/*
// 		   {
// 		       name: "test_case_1",
// 		       args: args {
// 		           p:nil,
// 		       },
// 		       want: want{},
// 		       checkFunc: defaultCheckFunc,
// 		       beforeFunc: func(t *testing.T, args args) {
// 		           t.Helper()
// 		       },
// 		       afterFunc: func(t *testing.T, args args) {
// 		           t.Helper()
// 		       },
// 		   },
// 		*/
//
// 		// TODO test cases
// 		/*
// 		   func() test {
// 		       return test {
// 		           name: "test_case_2",
// 		           args: args {
// 		           p:nil,
// 		           },
// 		           want: want{},
// 		           checkFunc: defaultCheckFunc,
// 		           beforeFunc: func(t *testing.T, args args) {
// 		               t.Helper()
// 		           },
// 		           afterFunc: func(t *testing.T, args args) {
// 		               t.Helper()
// 		           },
// 		       }
// 		   }(),
// 		*/
// 	}
//
// 	for _, tc := range tests {
// 		test := tc
// 		t.Run(test.name, func(tt *testing.T) {
// 			tt.Parallel()
// 			defer goleak.VerifyNone(tt, goleak.IgnoreCurrent())
// 			if test.beforeFunc != nil {
// 				test.beforeFunc(tt, test.args)
// 			}
// 			if test.afterFunc != nil {
// 				defer test.afterFunc(tt, test.args)
// 			}
// 			checkFunc := test.checkFunc
// 			if test.checkFunc == nil {
// 				checkFunc = defaultCheckFunc
// 			}
//
// 			got := responsePod(test.args.p)
// 			if err := checkFunc(test.want, got); err != nil {
// 				tt.Errorf("error = %v", err)
// 			}
// 		})
// 	}
// }
//
// func Test_stripResponsePodNodes(t *testing.T) {
// 	type args struct {
// 		ps *payload.Info_Pods
// 	}
// 	type want struct{}
// 	type test struct {
// 		name       string
// 		args       args
// 		want       want
// 		checkFunc  func(want) error
// 		beforeFunc func(*testing.T, args)
// 		afterFunc  func(*testing.T, args)
// 	}
// 	defaultCheckFunc := func(w want) error {
// 		return nil
// 	}
// 	tests := []test{
// 		// TODO test cases
// 		/*
// 		   {
// 		       name: "test_case_1",
// 		       args: args {
// 		           ps:nil,
// 		       },
// 		       want: want{},
// 		       checkFunc: defaultCheckFunc,
// 		       beforeFunc: func(t *testing.T, args args) {
// 		           t.Helper()
// 		       },
// 		       afterFunc: func(t *testing.T, args args) {
// 		           t.Helper()
// 		       },
// 		   },
// 		*/
//
// 		// TODO test cases
// 		/*
// 		   func() test {
// 		       return test {
// 		           name: "test_case_2",
// 		           args: args {
// 		           ps:nil,
// 		           },
// 		           want: want{},
// 		           checkFunc: defaultCheckFunc,
// 		           beforeFunc: func(t *testing.T, args args) {
// 		               t.Helper()
// 		           },
// 		           afterFunc: func(t *testing.T, args args) {
// 		               t.Helper()
// 		           },
// 		       }
// 		   }(),
// 		*/
// 	}
//
// 	for _, tc := range tests {
// 		test := tc
// 		t.Run(test.name, func(tt *testing.T) {
// 			tt.Parallel()
// 			defer goleak.VerifyNone(tt, goleak.IgnoreCurrent())
// 			if test.beforeFunc != nil {
// 				test.beforeFunc(tt, test.args)
// 			}
// 			if test.afterFunc != nil {
// 				defer test.afterFunc(tt, test.args)
// 			}
// 			checkFunc := test.checkFunc
// 			if test.checkFunc == nil {
// 				checkFunc = defaultCheckFunc
// 			}
//
// 			stripResponsePodNodes(test.args.ps)
// 			if err := checkFunc(test.want); err != nil {
// 				tt.Errorf("error = %v", err)
// 			}
// 		})
// 	}
// }
//
// func Test_discoverer_GetPods(t *testing.T) {
// 	type args struct {
// 		req *payload.Discoverer_Request
// 	}
// 	type fields struct {
// 		eg              errgroup.Group
// 		der             net.Dialer
// 		ctrl            k8s.Controller
// 		podsByName      atomic.Pointer[map[string][]*payload.Info_Pod]
// 		svcsByName      atomic.Pointer[map[string]*payload.Info_Service]
// 		nodeByName      atomic.Pointer[map[string]*payload.Info_Node]
// 		podsByNode      atomic.Pointer[map[string]map[string]map[string][]*payload.Info_Pod]
// 		podsByNamespace atomic.Pointer[map[string]map[string][]*payload.Info_Pod]
// 		namespace       string
// 		name            string
// 		pods            sync.Map[string, *[]Pod]
// 		nodeMetrics     sync.Map[string, NodeMetrics]
// 		nodes           sync.Map[string, *Node]
// 		podMetrics      sync.Map[string, PodMetrics]
// 		maxPods         int
// 		csd             time.Duration
// 	}
// 	type want struct {
// 		wantPods *payload.Info_Pods
// 		err      error
// 	}
// 	type test struct {
// 		name       string
// 		args       args
// 		fields     fields
// 		want       want
// 		checkFunc  func(want, *payload.Info_Pods, error) error
// 		beforeFunc func(*testing.T, args)
// 		afterFunc  func(*testing.T, args)
// 	}
// 	defaultCheckFunc := func(w want, gotPods *payload.Info_Pods, err error) error {
// 		if !errors.Is(err, w.err) {
// 			return errors.Errorf("got_error: \"%#v\",\n\t\t\t\twant: \"%#v\"", err, w.err)
// 		}
// 		if !reflect.DeepEqual(gotPods, w.wantPods) {
// 			return errors.Errorf("got: \"%#v\",\n\t\t\t\twant: \"%#v\"", gotPods, w.wantPods)
// 		}
// 		return nil
// 	}
// 	tests := []test{
// 		// TODO test cases
// 		/*
// 		   {
// 		       name: "test_case_1",
// 		       args: args {
// 		           req:nil,
// 		       },
// 		       fields: fields {
// 		           eg:nil,
// 		           der:nil,
// 		           ctrl:nil,
// 		           podsByName:nil,
// 		           svcsByName:nil,
// 		           nodeByName:nil,
// 		           podsByNode:nil,
// 		           podsByNamespace:nil,
// 		           namespace:"",
// 		           name:"",
// 		           pods:nil,
// 		           nodeMetrics:nil,
// 		           nodes:nil,
// 		           podMetrics:nil,
// 		           maxPods:0,
// 		           csd:nil,
// 		       },
// 		       want: want{},
// 		       checkFunc: defaultCheckFunc,
// 		       beforeFunc: func(t *testing.T, args args) {
// 		           t.Helper()
// 		       },
// 		       afterFunc: func(t *testing.T, args args) {
// 		           t.Helper()
// 		       },
// 		   },
// 		*/
//
// 		// TODO test cases
// 		/*
// 		   func() test {
// 		       return test {
// 		           name: "test_case_2",
// 		           args: args {
// 		           req:nil,
// 		           },
// 		           fields: fields {
// 		           eg:nil,
// 		           der:nil,
// 		           ctrl:nil,
// 		           podsByName:nil,
// 		           svcsByName:nil,
// 		           nodeByName:nil,
// 		           podsByNode:nil,
// 		           podsByNamespace:nil,
// 		           namespace:"",
// 		           name:"",
// 		           pods:nil,
// 		           nodeMetrics:nil,
// 		           nodes:nil,
// 		           podMetrics:nil,
// 		           maxPods:0,
// 		           csd:nil,
// 		           },
// 		           want: want{},
// 		           checkFunc: defaultCheckFunc,
// 		           beforeFunc: func(t *testing.T, args args) {
// 		               t.Helper()
// 		           },
// 		           afterFunc: func(t *testing.T, args args) {
// 		               t.Helper()
// 		           },
// 		       }
// 		   }(),
// 		*/
// 	}
//
// 	for _, tc := range tests {
// 		test := tc
// 		t.Run(test.name, func(tt *testing.T) {
// 			tt.Parallel()
// 			defer goleak.VerifyNone(tt, goleak.IgnoreCurrent())
// 			if test.beforeFunc != nil {
// 				test.beforeFunc(tt, test.args)
// 			}
// 			if test.afterFunc != nil {
// 				defer test.afterFunc(tt, test.args)
// 			}
// 			checkFunc := test.checkFunc
// 			if test.checkFunc == nil {
// 				checkFunc = defaultCheckFunc
// 			}
// 			d := &discoverer{
// 				eg:              test.fields.eg,
// 				der:             test.fields.der,
// 				ctrl:            test.fields.ctrl,
// 				podsByName:      test.fields.podsByName,
// 				svcsByName:      test.fields.svcsByName,
// 				nodeByName:      test.fields.nodeByName,
// 				podsByNode:      test.fields.podsByNode,
// 				podsByNamespace: test.fields.podsByNamespace,
// 				namespace:       test.fields.namespace,
// 				name:            test.fields.name,
// 				pods:            test.fields.pods,
// 				nodeMetrics:     test.fields.nodeMetrics,
// 				nodes:           test.fields.nodes,
// 				podMetrics:      test.fields.podMetrics,
// 				maxPods:         test.fields.maxPods,
// 				csd:             test.fields.csd,
// 			}
//
// 			gotPods, err := d.GetPods(test.args.req)
// 			if err := checkFunc(test.want, gotPods, err); err != nil {
// 				tt.Errorf("error = %v", err)
// 			}
// 		})
// 	}
// }
//
// func Test_discoverer_GetNodes(t *testing.T) {
// 	type args struct {
// 		req *payload.Discoverer_Request
// 	}
// 	type fields struct {
// 		eg              errgroup.Group
// 		der             net.Dialer
// 		ctrl            k8s.Controller
// 		podsByName      atomic.Pointer[map[string][]*payload.Info_Pod]
// 		svcsByName      atomic.Pointer[map[string]*payload.Info_Service]
// 		nodeByName      atomic.Pointer[map[string]*payload.Info_Node]
// 		podsByNode      atomic.Pointer[map[string]map[string]map[string][]*payload.Info_Pod]
// 		podsByNamespace atomic.Pointer[map[string]map[string][]*payload.Info_Pod]
// 		namespace       string
// 		name            string
// 		pods            sync.Map[string, *[]Pod]
// 		nodeMetrics     sync.Map[string, NodeMetrics]
// 		nodes           sync.Map[string, *Node]
// 		podMetrics      sync.Map[string, PodMetrics]
// 		maxPods         int
// 		csd             time.Duration
// 	}
// 	type want struct {
// 		wantNodes *payload.Info_Nodes
// 		err       error
// 	}
// 	type test struct {
// 		name       string
// 		args       args
// 		fields     fields
// 		want       want
// 		checkFunc  func(want, *payload.Info_Nodes, error) error
// 		beforeFunc func(*testing.T, args)
// 		afterFunc  func(*testing.T, args)
// 	}
// 	defaultCheckFunc := func(w want, gotNodes *payload.Info_Nodes, err error) error {
// 		if !errors.Is(err, w.err) {
// 			return errors.Errorf("got_error: \"%#v\",\n\t\t\t\twant: \"%#v\"", err, w.err)
// 		}
// 		if !reflect.DeepEqual(gotNodes, w.wantNodes) {
// 			return errors.Errorf("got: \"%#v\",\n\t\t\t\twant: \"%#v\"", gotNodes, w.wantNodes)
// 		}
// 		return nil
// 	}
// 	tests := []test{
// 		// TODO test cases
// 		/*
// 		   {
// 		       name: "test_case_1",
// 		       args: args {
// 		           req:nil,
// 		       },
// 		       fields: fields {
// 		           eg:nil,
// 		           der:nil,
// 		           ctrl:nil,
// 		           podsByName:nil,
// 		           svcsByName:nil,
// 		           nodeByName:nil,
// 		           podsByNode:nil,
// 		           podsByNamespace:nil,
// 		           namespace:"",
// 		           name:"",
// 		           pods:nil,
// 		           nodeMetrics:nil,
// 		           nodes:nil,
// 		           podMetrics:nil,
// 		           maxPods:0,
// 		           csd:nil,
// 		       },
// 		       want: want{},
// 		       checkFunc: defaultCheckFunc,
// 		       beforeFunc: func(t *testing.T, args args) {
// 		           t.Helper()
// 		       },
// 		       afterFunc: func(t *testing.T, args args) {
// 		           t.Helper()
// 		       },
// 		   },
// 		*/
//
// 		// TODO test cases
// 		/*
// 		   func() test {
// 		       return test {
// 		           name: "test_case_2",
// 		           args: args {
// 		           req:nil,
// 		           },
// 		           fields: fields {
// 		           eg:nil,
// 		           der:nil,
// 		           ctrl:nil,
// 		           podsByName:nil,
// 		           svcsByName:nil,
// 		           nodeByName:nil,
// 		           podsByNode:nil,
// 		           podsByNamespace:nil,
// 		           namespace:"",
// 		           name:"",
// 		           pods:nil,
// 		           nodeMetrics:nil,
// 		           nodes:nil,
// 		           podMetrics:nil,
// 		           maxPods:0,
// 		           csd:nil,
// 		           },
// 		           want: want{},
// 		           checkFunc: defaultCheckFunc,
// 		           beforeFunc: func(t *testing.T, args args) {
// 		               t.Helper()
// 		           },
// 		           afterFunc: func(t *testing.T, args args) {
// 		               t.Helper()
// 		           },
// 		       }
// 		   }(),
// 		*/
// 	}
//
// 	for _, tc := range tests {
// 		test := tc
// 		t.Run(test.name, func(tt *testing.T) {
// 			tt.Parallel()
// 			defer goleak.VerifyNone(tt, goleak.IgnoreCurrent())
// 			if test.beforeFunc != nil {
// 				test.beforeFunc(tt, test.args)
// 			}
// 			if test.afterFunc != nil {
// 				defer test.afterFunc(tt, test.args)
// 			}
// 			checkFunc := test.checkFunc
// 			if test.checkFunc == nil {
// 				checkFunc = defaultCheckFunc
// 			}
// 			d := &discoverer{
// 				eg:              test.fields.eg,
// 				der:             test.fields.der,
// 				ctrl:            test.fields.ctrl,
// 				podsByName:      test.fields.podsByName,
// 				svcsByName:      test.fields.svcsByName,
// 				nodeByName:      test.fields.nodeByName,
// 				podsByNode:      test.fields.podsByNode,
// 				podsByNamespace: test.fields.podsByNamespace,
// 				namespace:       test.fields.namespace,
// 				name:            test.fields.name,
// 				pods:            test.fields.pods,
// 				nodeMetrics:     test.fields.nodeMetrics,
// 				nodes:           test.fields.nodes,
// 				podMetrics:      test.fields.podMetrics,
// 				maxPods:         test.fields.maxPods,
// 				csd:             test.fields.csd,
// 			}
//
// 			gotNodes, err := d.GetNodes(test.args.req)
// 			if err := checkFunc(test.want, gotNodes, err); err != nil {
// 				tt.Errorf("error = %v", err)
// 			}
// 		})
// 	}
// }
//
// func Test_discoverer_GetServices(t *testing.T) {
// 	type args struct {
// 		req *payload.Discoverer_Request
// 	}
// 	type fields struct {
// 		eg              errgroup.Group
// 		der             net.Dialer
// 		ctrl            k8s.Controller
// 		podsByName      atomic.Pointer[map[string][]*payload.Info_Pod]
// 		svcsByName      atomic.Pointer[map[string]*payload.Info_Service]
// 		nodeByName      atomic.Pointer[map[string]*payload.Info_Node]
// 		podsByNode      atomic.Pointer[map[string]map[string]map[string][]*payload.Info_Pod]
// 		podsByNamespace atomic.Pointer[map[string]map[string][]*payload.Info_Pod]
// 		namespace       string
// 		name            string
// 		pods            sync.Map[string, *[]Pod]
// 		nodeMetrics     sync.Map[string, NodeMetrics]
// 		nodes           sync.Map[string, *Node]
// 		podMetrics      sync.Map[string, PodMetrics]
// 		maxPods         int
// 		csd             time.Duration
// 	}
// 	type want struct {
// 		wantSvcs *payload.Info_Services
// 		err      error
// 	}
// 	type test struct {
// 		name       string
// 		args       args
// 		fields     fields
// 		want       want
// 		checkFunc  func(want, *payload.Info_Services, error) error
// 		beforeFunc func(*testing.T, args)
// 		afterFunc  func(*testing.T, args)
// 	}
// 	defaultCheckFunc := func(w want, gotSvcs *payload.Info_Services, err error) error {
// 		if !errors.Is(err, w.err) {
// 			return errors.Errorf("got_error: \"%#v\",\n\t\t\t\twant: \"%#v\"", err, w.err)
// 		}
// 		if !reflect.DeepEqual(gotSvcs, w.wantSvcs) {
// 			return errors.Errorf("got: \"%#v\",\n\t\t\t\twant: \"%#v\"", gotSvcs, w.wantSvcs)
// 		}
// 		return nil
// 	}
// 	tests := []test{
// 		// TODO test cases
// 		/*
// 		   {
// 		       name: "test_case_1",
// 		       args: args {
// 		           req:nil,
// 		       },
// 		       fields: fields {
// 		           eg:nil,
// 		           der:nil,
// 		           ctrl:nil,
// 		           podsByName:nil,
// 		           svcsByName:nil,
// 		           nodeByName:nil,
// 		           podsByNode:nil,
// 		           podsByNamespace:nil,
// 		           namespace:"",
// 		           name:"",
// 		           pods:nil,
// 		           nodeMetrics:nil,
// 		           nodes:nil,
// 		           podMetrics:nil,
// 		           maxPods:0,
// 		           csd:nil,
// 		       },
// 		       want: want{},
// 		       checkFunc: defaultCheckFunc,
// 		       beforeFunc: func(t *testing.T, args args) {
// 		           t.Helper()
// 		       },
// 		       afterFunc: func(t *testing.T, args args) {
// 		           t.Helper()
// 		       },
// 		   },
// 		*/
//
// 		// TODO test cases
// 		/*
// 		   func() test {
// 		       return test {
// 		           name: "test_case_2",
// 		           args: args {
// 		           req:nil,
// 		           },
// 		           fields: fields {
// 		           eg:nil,
// 		           der:nil,
// 		           ctrl:nil,
// 		           podsByName:nil,
// 		           svcsByName:nil,
// 		           nodeByName:nil,
// 		           podsByNode:nil,
// 		           podsByNamespace:nil,
// 		           namespace:"",
// 		           name:"",
// 		           pods:nil,
// 		           nodeMetrics:nil,
// 		           nodes:nil,
// 		           podMetrics:nil,
// 		           maxPods:0,
// 		           csd:nil,
// 		           },
// 		           want: want{},
// 		           checkFunc: defaultCheckFunc,
// 		           beforeFunc: func(t *testing.T, args args) {
// 		               t.Helper()
// 		           },
// 		           afterFunc: func(t *testing.T, args args) {
// 		               t.Helper()
// 		           },
// 		       }
// 		   }(),
// 		*/
// 	}
//
// 	for _, tc := range tests {
// 		test := tc
// 		t.Run(test.name, func(tt *testing.T) {
// 			tt.Parallel()
// 			defer goleak.VerifyNone(tt, goleak.IgnoreCurrent())
// 			if test.beforeFunc != nil {
// 				test.beforeFunc(tt, test.args)
// 			}
// 			if test.afterFunc != nil {
// 				defer test.afterFunc(tt, test.args)
// 			}
// 			checkFunc := test.checkFunc
// 			if test.checkFunc == nil {
// 				checkFunc = defaultCheckFunc
// 			}
// 			d := &discoverer{
// 				eg:              test.fields.eg,
// 				der:             test.fields.der,
// 				ctrl:            test.fields.ctrl,
// 				podsByName:      test.fields.podsByName,
// 				svcsByName:      test.fields.svcsByName,
// 				nodeByName:      test.fields.nodeByName,
// 				podsByNode:      test.fields.podsByNode,
// 				podsByNamespace: test.fields.podsByNamespace,
// 				namespace:       test.fields.namespace,
// 				name:            test.fields.name,
// 				pods:            test.fields.pods,
// 				nodeMetrics:     test.fields.nodeMetrics,
// 				nodes:           test.fields.nodes,
// 				podMetrics:      test.fields.podMetrics,
// 				maxPods:         test.fields.maxPods,
// 				csd:             test.fields.csd,
// 			}
//
// 			gotSvcs, err := d.GetServices(test.args.req)
// 			if err := checkFunc(test.want, gotSvcs, err); err != nil {
// 				tt.Errorf("error = %v", err)
// 			}
// 		})
// 	}
// }
