{
 "title": "Vald Cluster Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "ReplicaSet",
    "label": "name",
    "query": "label_values(app_version_info, kubernetes_name)"
   },
   {
    "name": "ValdAgentPodName",
    "label": "agent-pod",
    "query": "label_values(agent_core_ngt_is_indexing{kubernetes_name =~\"vald-agent\"}, target_pod)"
   },
   {
    "name": "ValdAgentContainerName",
    "label": "agent-container",
    "query": "label_values(agent_core_ngt_is_indexing{kubernetes_name =~\"vald-agent\", target_pod=~\"$ValdAgentPodName\"}, container)"
   },
   {
    "name": "ValdGatewayPodName",
    "label": "gateway-pod",
    "query": "label_values(app_version_info{kubernetes_name=~\"vald-lb-gateway\"}, target_pod)"
   },
   {
    "name": "ValdGatewayContainerName",
    "label": "gateway-container",
    "query": "label_values(app_version_info{kubernetes_name =~\"vald-lb-gateway\", target_pod=~\"$ValdGatewayPodName\"}, container)"
   },
   { "name": "interval", "label": "interval", "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Vald Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_version_info{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\"}"
    }
   ]
  },
  {
   "title": "Go Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_version_info{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\"}"
    }
   ]
  },
  {
   "title": "Go OS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_version_info{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\"}"
    }
   ]
  },
  {
   "title": "Pods ($ReplicaSet)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"$Namespace\",pod=~\"$ReplicaSet.*\"})"
    }
   ]
  },
  {
   "title": "Total memory working set ($ReplicaSet)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$Namespace\",container=~\"$ReplicaSet\",image!=\"\"})"
    }
   ]
  },
  {
   "title": "Git Commit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_version_info{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\"}"
    }
   ]
  },
  {
   "title": "Built at",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_version_info{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\"}"
    }
   ]
  },
  {
   "title": "Indices",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(agent_core_ngt_index_count{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$ValdAgentPodName\"})"
    }
   ]
  },
  {
   "title": "Node CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Completed RPCs (Vald LB Gateway: $ValdGatewayPodName)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (grpc_server_method, grpc_server_status) (irate(server_completed_rpcs{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\"}[$interval]))",
     "legendFormat": "{{grpc_server_method}} ({{grpc_server_status}})"
    },
    {
     "expr": "sum by (grpc_server_status) (irate(server_completed_rpcs{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\"}[$interval]))",
     "legendFormat": "Total ({{grpc_server_status}})"
    }
   ]
  },
  {
   "title": "Latency (Vald LB Gateway: $ValdGatewayPodName)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, grpc_server_method) (rate(server_latency_bucket{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\",container=~\"$ValdGatewayContainerName\",grpc_server_method=~\".*\"}[$interval])))",
     "legendFormat": "{{grpc_server_method}} p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, grpc_server_method) (rate(server_latency_bucket{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\",container=~\"$ValdGatewayContainerName\",grpc_server_method=~\".*\"}[$interval])))",
     "legendFormat": "{{grpc_server_method}} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, grpc_server_method) (rate(server_latency_bucket{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\",container=~\"$ValdGatewayContainerName\",grpc_server_method=~\".*\"}[$interval])))",
     "legendFormat": "{{grpc_server_method}} p99"
    }
   ]
  },
  {
   "title": "Completed RPCs (Vald Agent: $ValdAgentPodName)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (grpc_server_method, grpc_server_status) (irate(server_completed_rpcs{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\"}[$interval]))",
     "legendFormat": "{{grpc_server_method}} ({{grpc_server_status}})"
    },
    {
     "expr": "sum by (grpc_server_status) (irate(server_completed_rpcs{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\"}[$interval]))",
     "legendFormat": "Total ({{grpc_server_status}})"
    }
   ]
  },
  {
   "title": "Latency (Vald Agent: $ValdAgentPodName)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, grpc_server_method) (rate(server_latency_bucket{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\",container=~\"$ValdAgentContainerName\",grpc_server_method!~\".*Index$\"}[$interval])))",
     "legendFormat": "{{grpc_server_method}} p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, grpc_server_method) (rate(server_latency_bucket{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\",container=~\"$ValdAgentContainerName\",grpc_server_method!~\".*Index$\"}[$interval])))",
     "legendFormat": "{{grpc_server_method}} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, grpc_server_method) (rate(server_latency_bucket{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\",container=~\"$ValdAgentContainerName\",grpc_server_method!~\".*Index$\"}[$interval])))",
     "legendFormat": "{{grpc_server_method}} p99"
    }
   ]
  },
  {
   "title": "Backoff Retry Count (Vald LB Gateway)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "increase((sum by (rpc) (label_replace(backoff_retry_count{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$ValdGatewayPodName\",backoff_name!~\"github.com/.*\"}, \"rpc\", \"$1\", \"backoff_name\", \"(.*/.*)/.*\")))[$interval:])",
     "legendFormat": "{{rpc}}"
    }
   ]
  },
  {
   "title": "Backoff Retry Count / Agent Completed RPCs (Vald LB Gateway)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "(increase((sum by (rpc) (label_replace(backoff_retry_count{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$ValdGatewayPodName\",backoff_name!~\"github.com/.*\"}, \"rpc\", \"$1\", \"backoff_name\", \"(.*/.*)/.*\")))[$interval:])) / (sum by (grpc_server_method) (irate(server_completed_rpcs{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$ValdAgentPodName\"}[$interval])))",
     "legendFormat": "{{grpc_server_method}} ({{grpc_server_status}})"
    }
   ]
  },
  {
   "title": "Circuit Breaker State (Vald LB Gateway)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "increase((sum by (rpc, state) (label_replace(circuit_breaker_state{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$ValdGatewayPodName\",state=\"open\"}, \"rpc\", \"$1\", \"name\", \"(.*/.*)/.*\")))[$interval:])",
     "legendFormat": "{{rpc}} ({{state}})"
    },
    {
     "expr": "increase((sum by (rpc, state) (label_replace(circuit_breaker_state{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$ValdGatewayPodName\",state=\"half-open\"}, \"rpc\", \"$1\", \"name\", \"(.*/.*)/.*\")))[$interval:])",
     "legendFormat": "{{rpc}} ({{state}})"
    }
   ]
  },
  {
   "title": "Latency (Vald Agent Index: $ValdAgentPodName)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, grpc_server_method) (rate(server_latency_bucket{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\",container=~\"$ValdAgentContainerName\",grpc_server_method=~\".*Index$\"}[$interval])))",
     "legendFormat": "{{grpc_server_method}} p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, grpc_server_method) (rate(server_latency_bucket{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\",container=~\"$ValdAgentContainerName\",grpc_server_method=~\".*Index$\"}[$interval])))",
     "legendFormat": "{{grpc_server_method}} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, grpc_server_method) (rate(server_latency_bucket{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\",container=~\"$ValdAgentContainerName\",grpc_server_method=~\".*Index$\"}[$interval])))",
     "legendFormat": "{{grpc_server_method}} p99"
    }
   ]
  },
  { "title": "$ReplicaSet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }, "repeat": "ReplicaSet" },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"$Namespace\",pod=~\"$ReplicaSet.*\"})"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 3, "y": 45 },
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{namespace=\"$Namespace\",deployment=\"$ReplicaSet\"})",
     "legendFormat": "replicas"
    },
    {
     "expr": "max(kube_deployment_status_replicas_available{namespace=\"$Namespace\",deployment=\"$ReplicaSet\"})",
     "legendFormat": "replicas_available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{namespace=\"$Namespace\",deployment=\"$ReplicaSet\"})",
     "legendFormat": "replicas_unavailable"
    },
    {
     "expr": "max(kube_deployment_status_replicas_updated{namespace=\"$Namespace\",deployment=\"$ReplicaSet\"})",
     "legendFormat": "replicas_updated"
    },
    {
     "expr": "max(kube_daemonset_status_current_number_scheduled{namespace=\"$Namespace\",daemonset=\"$ReplicaSet\"})",
     "legendFormat": "current_number_scheduled"
    },
    {
     "expr": "max(kube_daemonset_status_desired_number_scheduled{namespace=\"$Namespace\",daemonset=\"$ReplicaSet\"})",
     "legendFormat": "desired_number_scheduled"
    },
    {
     "expr": "max(kube_daemonset_status_number_available{namespace=\"$Namespace\",daemonset=\"$ReplicaSet\"})",
     "legendFormat": "number_available"
    },
    {
     "expr": "max(kube_daemonset_status_number_misscheduled{namespace=\"$Namespace\",daemonset=\"$ReplicaSet\"})",
     "legendFormat": "number_misscheduled"
    },
    {
     "expr": "max(kube_daemonset_status_number_ready{namespace=\"$Namespace\",daemonset=\"$ReplicaSet\"})",
     "legendFormat": "number_ready"
    },
    {
     "expr": "max(kube_daemonset_status_number_unavailable{namespace=\"$Namespace\",daemonset=\"$ReplicaSet\"})",
     "legendFormat": "number_unavailable"
    },
    {
     "expr": "max(kube_statefulset_status_replicas_current{namespace=\"$Namespace\",statefulset=\"$ReplicaSet\"})",
     "legendFormat": "replicas_current"
    },
    {
     "expr": "max(kube_statefulset_status_replicas_ready{namespace=\"$Namespace\",statefulset=\"$ReplicaSet\"})",
     "legendFormat": "replicas_ready"
    },
    {
     "expr": "max(kube_statefulset_status_replicas_updated{namespace=\"$Namespace\",statefulset=\"$ReplicaSet\"})",
     "legendFormat": "replicas_updated"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{namespace=\"$Namespace\",pod=~\"$ReplicaSet.*\",image!=\"\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Memory Working Set",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(sum by (pod) (container_memory_working_set_bytes{namespace=\"$Namespace\",pod=~\"$ReplicaSet.*\",image!=\"\"}))"
    }
   ]
  }
 ]
}