{
 "title": "Vald Helm Operator",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "ReplicaSet",
    "label": "name",
    "query": "label_values(helm_operator_build_info{namespace=~\"$Namespace\"}, app_kubernetes_io_name)"
   },
   {
    "name": "PodName",
    "label": "pod",
    "query": "label_values(helm_operator_build_info{namespace=~\"$Namespace\", app_kubernetes_io_name=~\"$ReplicaSet\"}, instance)"
   },
   { "name": "interval", "label": "interval", "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Operator SDK Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "helm_operator_build_info{namespace=~\"$Namespace\", app_kubernetes_io_name=\"$ReplicaSet\", instance=~\"$PodName\"}"
    }
   ]
  },
  {
   "title": "Go Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_info{namespace=~\"$Namespace\", app_kubernetes_io_name=~\"$ReplicaSet\", instance=~\"$PodName\"}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "resource_created_at_seconds{namespace=~\"$Namespace\", app_kubernetes_io_name=~\"$ReplicaSet\", instance=~\"$PodName\"}"
    }
   ]
  },
  {
   "title": "Reconcile Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(irate(controller_runtime_reconcile_total{namespace=~\"$Namespace\", app_kubernetes_io_name=~\"$ReplicaSet\", instance=~\"$PodName\"}[$interval])) by (controller, result)",
     "legendFormat": "{{controller}} ({{result}})"
    }
   ]
  },
  {
   "title": "Reconcile Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(irate(controller_runtime_reconcile_errors_total{namespace=~\"$Namespace\", app_kubernetes_io_name=~\"$ReplicaSet\", instance=~\"$PodName\"}[5m])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(controller_runtime_reconcile_time_seconds_bucket{namespace=~\"$Namespace\", app_kubernetes_io_name=~\"$ReplicaSet\", instance=~\"$PodName\"}[$interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.950000, sum(rate(controller_runtime_reconcile_time_seconds_bucket{namespace=~\"$Namespace\", app_kubernetes_io_name=~\"$ReplicaSet\", instance=~\"$PodName\"}[$interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(controller_runtime_reconcile_time_seconds_bucket{namespace=~\"$Namespace\", app_kubernetes_io_name=~\"$ReplicaSet\", instance=~\"$PodName\"}[$interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "K8S Server API Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(rest_client_request_duration_seconds_bucket{namespace=~\"$Namespace\"}[$interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.950000, sum(rate(rest_client_request_duration_seconds_bucket{namespace=~\"$Namespace\"}[$interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(rest_client_request_duration_seconds_bucket{namespace=~\"$Namespace\"}[$interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}