{
 "title": "Vald LB Gateway",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "ReplicaSet",
    "label": "name",
    "query": "label_values(app_version_info{server_name=~\"gateway lb.*\"}, kubernetes_name)"
   },
   {
    "name": "PodName",
    "label": "pod",
    "query": "label_values(app_version_info{server_name=~\"gateway lb.*\", kubernetes_name=\"$ReplicaSet\"}, target_pod)"
   },
   {
    "name": "ContainerName",
    "label": "container",
    "query": "label_values(app_version_info{server_name=~\"gateway lb.*\", kubernetes_name=\"$ReplicaSet\", target_pod=~\"$PodName\"}, container)"
   },
   { "name": "interval", "label": "interval", "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Vald Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_version_info{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\"}"
    }
   ]
  },
  {
   "title": "Go Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_version_info{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\"}"
    }
   ]
  },
  {
   "title": "Go OS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_version_info{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\"}"
    }
   ]
  },
  {
   "title": "Pods ($ReplicaSet)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"$Namespace\",pod=~\"$ReplicaSet.*\"})"
    }
   ]
  },
  {
   "title": "Total memory working set ($ReplicaSet)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$Namespace\",container=~\"$ReplicaSet\",image!=\"\"})"
    }
   ]
  },
  {
   "title": "Git Commit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_version_info{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\"}"
    }
   ]
  },
  {
   "title": "Built at",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_version_info{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{namespace=\"$Namespace\",container=~\"$ReplicaSet\",pod=~\"$PodName\",image!=\"\"}[$interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"$Namespace\",container=\"$ReplicaSet\",pod=~\"$PodName\",image!=\"\"})",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "Completed RPCs ($PodName)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (grpc_server_method, grpc_server_status) (irate(server_completed_rpcs{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\"}[$interval]))",
     "legendFormat": "{{grpc_server_method}} ({{grpc_server_status}})"
    },
    {
     "expr": "sum by (grpc_server_status) (irate(server_completed_rpcs{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\"}[$interval]))",
     "legendFormat": "Total ({{grpc_server_status}})"
    }
   ]
  },
  {
   "title": "Latency ($PodName)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, grpc_server_method) (rate(server_latency_bucket{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\",container=~\"$ContainerName\",grpc_server_method=~\".*\"}[$interval])))",
     "legendFormat": "{{grpc_server_method}} p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, grpc_server_method) (rate(server_latency_bucket{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\",container=~\"$ContainerName\",grpc_server_method=~\".*\"}[$interval])))",
     "legendFormat": "{{grpc_server_method}} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le, grpc_server_method) (rate(server_latency_bucket{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\",container=~\"$ContainerName\",grpc_server_method=~\".*\"}[$interval])))",
     "legendFormat": "{{grpc_server_method}} p99"
    }
   ]
  },
  {
   "title": "Goroutine Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "goroutine_count{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_pod=~\"$PodName\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "increase(gc_count{exported_kubernetes_namespace=\"$Namespace\",kubernetes_name=~\"$ReplicaSet\",target_node=~\".+\"}[$interval])",
     "legendFormat": "{{target_pod}}"
    }
   ]
  }
 ]
}