{
 "title": "Vald Agent Memory",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "ReplicaSet",
    "label": "name",
    "query": "label_values(app_version_info{server_name=~\"agent .*\"}, kubernetes_name)"
   },
   {
    "name": "PodName",
    "label": "pod",
    "query": "label_values(app_version_info{server_name=~\"agent .*\", kubernetes_name=\"$ReplicaSet\"}, target_pod)"
   },
   {
    "name": "ContainerName",
    "label": "container",
    "query": "label_values(app_version_info{server_name=~\"agent .*\", kubernetes_name=\"$ReplicaSet\", target_pod=~\"$PodName\"}, container)"
   },
   { "name": "interval", "label": "interval", "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  { "title": "runtime.Memstats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alloc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "alloc_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "Total Alloc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "alloc_bytes_total{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "Sys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sys_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "Lookups",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "lookups_count{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "Mallocs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "mallocs_total{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "Frees",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "frees_total{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "HeapAlloc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "heap_alloc_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "HeapSys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "heap_sys_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "HeapIdle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "heap_idle_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "HeapInUse",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "heap_inuse_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "HeapReleased",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "heap_released_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "HeapObjects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "expr": "heap_objects_count{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "StackInUse",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "stack_inuse_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "StackSys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "stack_sys_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "MSpanInUse",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mspan_inuse_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "MSpanSys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mspan_sys_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "MCacheInUse",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mcache_inuse_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "MCacheSys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mcache_sys_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "BuckHashSys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "buckhash_sys_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "GCSys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "gc_sys_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "OtherSys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "other_sys_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "NextGC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "next_gc_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "PauseTotalMS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pause_ms_total{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "NumGC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "targets": [
    {
     "expr": "gc_count{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "NumForcedGC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "forced_gc_count{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "HeapWillReturn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "heap_will_return_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "LiveObjects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "live_objects_count{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  { "title": "/proc/<pid>/status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "VMPeak",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vmpeak_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "VMSize",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vmsize_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "VMData",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vmdata_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "VMRSS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vmrss_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "VMHWM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vmhwm_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "VMStk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vmstk_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "VMSwap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vmswap_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "VMExe",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vmexe_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "VMLib",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vmlib_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "VMLck",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vmlck_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "VMPin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vmpin_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  },
  {
   "title": "VMPTE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vmpte_bytes{exported_kubernetes_namespace=\"$Namespace\", target_pod=~\"$PodName\", kubernetes_name=~\"$ReplicaSet\"}",
     "legendFormat": "{{target_pod}}"
    }
   ]
  }
 ]
}