{
 "title": "Vald Cluster Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ReplicaSet",
    "query": "label_values(vald_app_version_info, job)"
   },
   {
    "name": "Node",
    "query": "label_values(vald_app_version_info{job=~\"$ReplicaSet\"}, node)"
   },
   {
    "name": "Pod",
    "query": "label_values(vald_app_version_info{job=~\"$ReplicaSet\"}, pod)"
   },
   {
    "name": "ValdAgentNGT",
    "query": "label_values(vald_app_version_info{server_name=\"agent ngt\"}, job)"
   },
   {
    "name": "ValdDiscovererK8s",
    "query": "label_values(vald_app_version_info{server_name=\"discoverer k8s\"}, job)"
   },
   {
    "name": "ValdGateway",
    "query": "label_values(vald_app_version_info{server_name=\"gateway vald\"}, job)"
   },
   {
    "name": "ValdManagerBackup",
    "query": "label_values(vald_app_version_info{server_name=~\"manager backup .*\"}, job)"
   },
   {
    "name": "ValdManagerCompressor",
    "query": "label_values(vald_app_version_info{server_name=\"manager compressor\"}, job)"
   },
   {
    "name": "ValdManagerIndex",
    "query": "label_values(vald_app_version_info{server_name=\"index manager\"}, job)"
   },
   {
    "name": "ValdMeta",
    "query": "label_values(vald_app_version_info{server_name=~\"meta .*\"}, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Vald Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "vald_app_version_info{job=~\"$ReplicaSet\", node=~\"$Node\" ,pod=~\"$Pod\"}"
    }
   ]
  },
  {
   "title": "Go Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "label_replace(vald_app_version_info{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"}, \"go_version\", \"v$1\", \"go_version\", \"([^v].*)\")"
    }
   ]
  },
  {
   "title": "Go OS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "vald_app_version_info{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"}"
    }
   ]
  },
  {
   "title": "Total memory alloc",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(vald_alloc_bytes{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"})"
    }
   ]
  },
  {
   "title": "Git Commit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "vald_app_version_info{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"}"
    }
   ]
  },
  {
   "title": "Build at",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "vald_app_version_info{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"}"
    }
   ]
  },
  {
   "title": "Agent Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count(up{job=~\"$ValdAgentNGT\", node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Discoverer Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "count(up{job=~\"$ValdDiscovererK8s\", node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Gateway Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "count(up{job=~\"$ValdGateway\", node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Backup Manager Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "count(up{job=~\"$ValdManagerBackup\", node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Compressor Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 6 },
   "targets": [
    {
     "expr": "count(up{job=~\"$ValdManagerCompressor\", node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Index Manager Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "count(up{job=~\"$ValdManagerIndex\", node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Meta Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
   "targets": [
    {
     "expr": "count(up{job=~\"$ValdMeta\", node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vald_cpu_utilization{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "memory alloc",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vald_alloc_bytes{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "goroutine count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vald_goroutine_count{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vald_gc_count{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}