{
 "title": "Vald Agent",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ReplicaSet",
    "query": "label_values(vald_ngt_is_indexing, job)"
   },
   {
    "name": "Node",
    "query": "label_values(vald_ngt_is_indexing, node)"
   },
   {
    "name": "Pod",
    "query": "label_values(vald_ngt_is_indexing, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Vald Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "vald_app_version_info{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"}"
    }
   ]
  },
  {
   "title": "Go Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "label_replace(vald_app_version_info{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"}, \"go_version\", \"v$1\", \"go_version\", \"([^v].*)\")"
    }
   ]
  },
  {
   "title": "NGT Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "label_replace(vald_app_version_info{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"}, \"ngt_version\", \"v$1\", \"ngt_version\", \"([^v].*)\")"
    }
   ]
  },
  {
   "title": "NGT uncommitted indices",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vald_ngt_uncommitted_index_count{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"})"
    }
   ]
  },
  {
   "title": "insert vcache",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vald_ngt_insert_vcache_count{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"})"
    }
   ]
  },
  {
   "title": "delete vcache",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vald_ngt_delete_vcache_count{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"})"
    }
   ]
  },
  {
   "title": "Git Commit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "vald_app_version_info{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"}"
    }
   ]
  },
  {
   "title": "Build at",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "vald_app_version_info{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"}"
    }
   ]
  },
  {
   "title": "NGT indices",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vald_ngt_index_count{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"})"
    }
   ]
  },
  {
   "title": "Indexing pods",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vald_ngt_is_indexing{job=~\"$ReplicaSet\", node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=~\"$ReplicaSet\", node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "NGT indices",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vald_ngt_index_count{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "NGT uncommitted indices",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vald_ngt_uncommitted_index_count{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"}",
     "legendFormat": "{{pod}}-uncommitted-indices"
    },
    {
     "expr": "vald_ngt_insert_vcache_count{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"}",
     "legendFormat": "{{pod}}-insert-vcache"
    },
    {
     "expr": "vald_ngt_delete_vcache_count{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"}",
     "legendFormat": "{{pod}}-delete-vcache"
    }
   ]
  },
  {
   "title": "goroutine count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vald_goroutine_count{job=~\"$ReplicaSet\", node=~\"$Node\", pod=~\"$Pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}