apiVersion: vald.vdaas.org/v1
kind: Mvaldrelease
metadata:
  labels:
    app.kubernetes.io/name: mvaldrelease
    app.kubernetes.io/managed-by: kustomize
  name: mvaldrelease-sample
spec:
  infrastructure:
    - role: "green"
      type: "kubernetes"
      active: true
      clusters:
        - id: "12345678-1234-1234-1234-123456789012"
          name: "lpokijhbgaev"
        - id: "87654321-4321-4321-4321-210987654321"
          name: "bhnjmktyuioi"
      nodePools:
        general:
          name: "node-pool-1-general"
          machineResource:
            name: "highmemory"
            cpu: "1"
            memory: "2Gi"
            storage: "10Gi"
          replicas: 1
        agent:
          name: "agent-pool-1-agent"
          machineResource:
            name: "highcpu"
            cpu: "1"
            memory: "2Gi"
            storage: "10Gi"
          replicas: 1
  vectorEngine:
    name: "vald"
    vald:
      defaults:
        logLevel: "info"
      agent:
        ngt:
          creationEdgeSize: 10
          searchEdgeSize: 40
          dimension: 128
          distanceType: "l2"
          objectType: float
        persistentVolume:
          enabled: true
      indexer:
        manager: false
        indexDuration: "24h"
        indexSchedule: "0 2 * * *"
        saveDuration: "1h"
        saveSchedule: "0 * * * *"
        concurrency: 2
      gateway:
        indexReplica: 2
      discoverer:
        kind: "Deployment"
      overlay:
        spec:
          discoverer:
            clusterRole:
              enabled: false
            clusterRoleBinding:
              enabled: false
          agent:
            ngt:
              dimension: 256
