//
// Copyright (C) 2019-2026 vdaas.org vald team <vald@vdaas.org>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/embedder/embedder.proto

package embedder

import (
	reflect "reflect"
	unsafe "unsafe"

	payload "github.com/vdaas/vald/apis/grpc/v1/payload"
	sync "github.com/vdaas/vald/internal/sync"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Text struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Text) Reset() {
	*x = Text{}
	mi := &file_v1_embedder_embedder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_v1_embedder_embedder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_v1_embedder_embedder_proto_rawDescGZIP(), []int{0}
}

func (x *Text) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_v1_embedder_embedder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_v1_embedder_embedder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_v1_embedder_embedder_proto_rawDescGZIP(), []int{1}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Document) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Config        *payload.Search_Config `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_v1_embedder_embedder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_embedder_embedder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_v1_embedder_embedder_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SearchRequest) GetConfig() *payload.Search_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Config        *payload.Insert_Config `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_v1_embedder_embedder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_embedder_embedder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_v1_embedder_embedder_proto_rawDescGZIP(), []int{3}
}

func (x *InsertRequest) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *InsertRequest) GetConfig() *payload.Insert_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type InsertWithMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *InsertRequest         `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Metadata      *payload.Meta_Value    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertWithMetadataRequest) Reset() {
	*x = InsertWithMetadataRequest{}
	mi := &file_v1_embedder_embedder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertWithMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertWithMetadataRequest) ProtoMessage() {}

func (x *InsertWithMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_embedder_embedder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertWithMetadataRequest.ProtoReflect.Descriptor instead.
func (*InsertWithMetadataRequest) Descriptor() ([]byte, []int) {
	return file_v1_embedder_embedder_proto_rawDescGZIP(), []int{4}
}

func (x *InsertWithMetadataRequest) GetRequest() *InsertRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *InsertWithMetadataRequest) GetMetadata() *payload.Meta_Value {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Config        *payload.Update_Config `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_v1_embedder_embedder_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_embedder_embedder_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_v1_embedder_embedder_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRequest) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *UpdateRequest) GetConfig() *payload.Update_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateWithMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *UpdateRequest         `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Metadata      *payload.Meta_Value    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWithMetadataRequest) Reset() {
	*x = UpdateWithMetadataRequest{}
	mi := &file_v1_embedder_embedder_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWithMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWithMetadataRequest) ProtoMessage() {}

func (x *UpdateWithMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_embedder_embedder_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWithMetadataRequest.ProtoReflect.Descriptor instead.
func (*UpdateWithMetadataRequest) Descriptor() ([]byte, []int) {
	return file_v1_embedder_embedder_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateWithMetadataRequest) GetRequest() *UpdateRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *UpdateWithMetadataRequest) GetMetadata() *payload.Meta_Value {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UpsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Config        *payload.Upsert_Config `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRequest) Reset() {
	*x = UpsertRequest{}
	mi := &file_v1_embedder_embedder_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRequest) ProtoMessage() {}

func (x *UpsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_embedder_embedder_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRequest.ProtoReflect.Descriptor instead.
func (*UpsertRequest) Descriptor() ([]byte, []int) {
	return file_v1_embedder_embedder_proto_rawDescGZIP(), []int{7}
}

func (x *UpsertRequest) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *UpsertRequest) GetConfig() *payload.Upsert_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpsertWithMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *UpsertRequest         `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Metadata      *payload.Meta_Value    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertWithMetadataRequest) Reset() {
	*x = UpsertWithMetadataRequest{}
	mi := &file_v1_embedder_embedder_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertWithMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertWithMetadataRequest) ProtoMessage() {}

func (x *UpsertWithMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_embedder_embedder_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertWithMetadataRequest.ProtoReflect.Descriptor instead.
func (*UpsertWithMetadataRequest) Descriptor() ([]byte, []int) {
	return file_v1_embedder_embedder_proto_rawDescGZIP(), []int{8}
}

func (x *UpsertWithMetadataRequest) GetRequest() *UpsertRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *UpsertWithMetadataRequest) GetMetadata() *payload.Meta_Value {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Config        *payload.Remove_Config `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_v1_embedder_embedder_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_embedder_embedder_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_v1_embedder_embedder_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveRequest) GetConfig() *payload.Remove_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_v1_embedder_embedder_proto protoreflect.FileDescriptor

const file_v1_embedder_embedder_proto_rawDesc = "" +
	"\n" +
	"\x1av1/embedder/embedder.proto\x12\vembedder.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x18v1/payload/payload.proto\"\x1a\n" +
	"\x04Text\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"L\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"V\n" +
	"\rSearchRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x121\n" +
	"\x06config\x18\x02 \x01(\v2\x19.payload.v1.Search.ConfigR\x06config\"u\n" +
	"\rInsertRequest\x121\n" +
	"\bdocument\x18\x01 \x01(\v2\x15.embedder.v1.DocumentR\bdocument\x121\n" +
	"\x06config\x18\x02 \x01(\v2\x19.payload.v1.Insert.ConfigR\x06config\"\x85\x01\n" +
	"\x19InsertWithMetadataRequest\x124\n" +
	"\arequest\x18\x01 \x01(\v2\x1a.embedder.v1.InsertRequestR\arequest\x122\n" +
	"\bmetadata\x18\x02 \x01(\v2\x16.payload.v1.Meta.ValueR\bmetadata\"u\n" +
	"\rUpdateRequest\x121\n" +
	"\bdocument\x18\x01 \x01(\v2\x15.embedder.v1.DocumentR\bdocument\x121\n" +
	"\x06config\x18\x02 \x01(\v2\x19.payload.v1.Update.ConfigR\x06config\"\x85\x01\n" +
	"\x19UpdateWithMetadataRequest\x124\n" +
	"\arequest\x18\x01 \x01(\v2\x1a.embedder.v1.UpdateRequestR\arequest\x122\n" +
	"\bmetadata\x18\x02 \x01(\v2\x16.payload.v1.Meta.ValueR\bmetadata\"u\n" +
	"\rUpsertRequest\x121\n" +
	"\bdocument\x18\x01 \x01(\v2\x15.embedder.v1.DocumentR\bdocument\x121\n" +
	"\x06config\x18\x02 \x01(\v2\x19.payload.v1.Upsert.ConfigR\x06config\"\x85\x01\n" +
	"\x19UpsertWithMetadataRequest\x124\n" +
	"\arequest\x18\x01 \x01(\v2\x1a.embedder.v1.UpsertRequestR\arequest\x122\n" +
	"\bmetadata\x18\x02 \x01(\v2\x16.payload.v1.Meta.ValueR\bmetadata\"R\n" +
	"\rRemoveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\x06config\x18\x02 \x01(\v2\x19.payload.v1.Remove.ConfigR\x06config2\xda\b\n" +
	"\bEmbedder\x12U\n" +
	"\x06Search\x12\x1a.embedder.v1.SearchRequest\x1a\x1b.payload.v1.Search.Response\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/search\x12a\n" +
	"\fLinearSearch\x12\x1a.embedder.v1.SearchRequest\x1a\x1b.payload.v1.Search.Response\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/linearsearch\x12U\n" +
	"\x06Insert\x12\x1a.embedder.v1.InsertRequest\x1a\x1b.payload.v1.Object.Location\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/insert\x12{\n" +
	"\x12InsertWithMetadata\x12&.embedder.v1.InsertWithMetadataRequest\x1a\x1b.payload.v1.Object.Location\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/insert/with-metadata\x12U\n" +
	"\x06Update\x12\x1a.embedder.v1.UpdateRequest\x1a\x1b.payload.v1.Object.Location\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/update\x12{\n" +
	"\x12UpdateWithMetadata\x12&.embedder.v1.UpdateWithMetadataRequest\x1a\x1b.payload.v1.Object.Location\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/update/with-metadata\x12U\n" +
	"\x06Upsert\x12\x1a.embedder.v1.UpsertRequest\x1a\x1b.payload.v1.Object.Location\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/upsert\x12{\n" +
	"\x12UpsertWithMetadata\x12&.embedder.v1.UpsertWithMetadataRequest\x1a\x1b.payload.v1.Object.Location\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/upsert/with-metadata\x12U\n" +
	"\x06Remove\x12\x1a.embedder.v1.RemoveRequest\x1a\x1b.payload.v1.Object.Location\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/remove\x12o\n" +
	"\x12RemoveWithMetadata\x12\x1a.embedder.v1.RemoveRequest\x1a\x1b.payload.v1.Object.Location\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/remove/with-metadata\x12P\n" +
	"\tEmbedding\x12\x11.embedder.v1.Text\x1a\x19.payload.v1.Object.Vector\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/embeddingB]\n" +
	"\x1eorg.vdaas.vald.api.v1.embedderB\fValdEmbedderP\x01Z+github.com/vdaas/vald/apis/grpc/v1/embedderb\x06proto3"

var (
	file_v1_embedder_embedder_proto_rawDescOnce sync.Once
	file_v1_embedder_embedder_proto_rawDescData []byte
)

func file_v1_embedder_embedder_proto_rawDescGZIP() []byte {
	file_v1_embedder_embedder_proto_rawDescOnce.Do(func() {
		file_v1_embedder_embedder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_embedder_embedder_proto_rawDesc), len(file_v1_embedder_embedder_proto_rawDesc)))
	})
	return file_v1_embedder_embedder_proto_rawDescData
}

var file_v1_embedder_embedder_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_v1_embedder_embedder_proto_goTypes = []any{
	(*Text)(nil),                      // 0: embedder.v1.Text
	(*Document)(nil),                  // 1: embedder.v1.Document
	(*SearchRequest)(nil),             // 2: embedder.v1.SearchRequest
	(*InsertRequest)(nil),             // 3: embedder.v1.InsertRequest
	(*InsertWithMetadataRequest)(nil), // 4: embedder.v1.InsertWithMetadataRequest
	(*UpdateRequest)(nil),             // 5: embedder.v1.UpdateRequest
	(*UpdateWithMetadataRequest)(nil), // 6: embedder.v1.UpdateWithMetadataRequest
	(*UpsertRequest)(nil),             // 7: embedder.v1.UpsertRequest
	(*UpsertWithMetadataRequest)(nil), // 8: embedder.v1.UpsertWithMetadataRequest
	(*RemoveRequest)(nil),             // 9: embedder.v1.RemoveRequest
	(*payload.Search_Config)(nil),     // 10: payload.v1.Search.Config
	(*payload.Insert_Config)(nil),     // 11: payload.v1.Insert.Config
	(*payload.Meta_Value)(nil),        // 12: payload.v1.Meta.Value
	(*payload.Update_Config)(nil),     // 13: payload.v1.Update.Config
	(*payload.Upsert_Config)(nil),     // 14: payload.v1.Upsert.Config
	(*payload.Remove_Config)(nil),     // 15: payload.v1.Remove.Config
	(*payload.Search_Response)(nil),   // 16: payload.v1.Search.Response
	(*payload.Object_Location)(nil),   // 17: payload.v1.Object.Location
	(*payload.Object_Vector)(nil),     // 18: payload.v1.Object.Vector
}
var file_v1_embedder_embedder_proto_depIdxs = []int32{
	10, // 0: embedder.v1.SearchRequest.config:type_name -> payload.v1.Search.Config
	1,  // 1: embedder.v1.InsertRequest.document:type_name -> embedder.v1.Document
	11, // 2: embedder.v1.InsertRequest.config:type_name -> payload.v1.Insert.Config
	3,  // 3: embedder.v1.InsertWithMetadataRequest.request:type_name -> embedder.v1.InsertRequest
	12, // 4: embedder.v1.InsertWithMetadataRequest.metadata:type_name -> payload.v1.Meta.Value
	1,  // 5: embedder.v1.UpdateRequest.document:type_name -> embedder.v1.Document
	13, // 6: embedder.v1.UpdateRequest.config:type_name -> payload.v1.Update.Config
	5,  // 7: embedder.v1.UpdateWithMetadataRequest.request:type_name -> embedder.v1.UpdateRequest
	12, // 8: embedder.v1.UpdateWithMetadataRequest.metadata:type_name -> payload.v1.Meta.Value
	1,  // 9: embedder.v1.UpsertRequest.document:type_name -> embedder.v1.Document
	14, // 10: embedder.v1.UpsertRequest.config:type_name -> payload.v1.Upsert.Config
	7,  // 11: embedder.v1.UpsertWithMetadataRequest.request:type_name -> embedder.v1.UpsertRequest
	12, // 12: embedder.v1.UpsertWithMetadataRequest.metadata:type_name -> payload.v1.Meta.Value
	15, // 13: embedder.v1.RemoveRequest.config:type_name -> payload.v1.Remove.Config
	2,  // 14: embedder.v1.Embedder.Search:input_type -> embedder.v1.SearchRequest
	2,  // 15: embedder.v1.Embedder.LinearSearch:input_type -> embedder.v1.SearchRequest
	3,  // 16: embedder.v1.Embedder.Insert:input_type -> embedder.v1.InsertRequest
	4,  // 17: embedder.v1.Embedder.InsertWithMetadata:input_type -> embedder.v1.InsertWithMetadataRequest
	5,  // 18: embedder.v1.Embedder.Update:input_type -> embedder.v1.UpdateRequest
	6,  // 19: embedder.v1.Embedder.UpdateWithMetadata:input_type -> embedder.v1.UpdateWithMetadataRequest
	7,  // 20: embedder.v1.Embedder.Upsert:input_type -> embedder.v1.UpsertRequest
	8,  // 21: embedder.v1.Embedder.UpsertWithMetadata:input_type -> embedder.v1.UpsertWithMetadataRequest
	9,  // 22: embedder.v1.Embedder.Remove:input_type -> embedder.v1.RemoveRequest
	9,  // 23: embedder.v1.Embedder.RemoveWithMetadata:input_type -> embedder.v1.RemoveRequest
	0,  // 24: embedder.v1.Embedder.Embedding:input_type -> embedder.v1.Text
	16, // 25: embedder.v1.Embedder.Search:output_type -> payload.v1.Search.Response
	16, // 26: embedder.v1.Embedder.LinearSearch:output_type -> payload.v1.Search.Response
	17, // 27: embedder.v1.Embedder.Insert:output_type -> payload.v1.Object.Location
	17, // 28: embedder.v1.Embedder.InsertWithMetadata:output_type -> payload.v1.Object.Location
	17, // 29: embedder.v1.Embedder.Update:output_type -> payload.v1.Object.Location
	17, // 30: embedder.v1.Embedder.UpdateWithMetadata:output_type -> payload.v1.Object.Location
	17, // 31: embedder.v1.Embedder.Upsert:output_type -> payload.v1.Object.Location
	17, // 32: embedder.v1.Embedder.UpsertWithMetadata:output_type -> payload.v1.Object.Location
	17, // 33: embedder.v1.Embedder.Remove:output_type -> payload.v1.Object.Location
	17, // 34: embedder.v1.Embedder.RemoveWithMetadata:output_type -> payload.v1.Object.Location
	18, // 35: embedder.v1.Embedder.Embedding:output_type -> payload.v1.Object.Vector
	25, // [25:36] is the sub-list for method output_type
	14, // [14:25] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_v1_embedder_embedder_proto_init() }
func file_v1_embedder_embedder_proto_init() {
	if File_v1_embedder_embedder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_embedder_embedder_proto_rawDesc), len(file_v1_embedder_embedder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_embedder_embedder_proto_goTypes,
		DependencyIndexes: file_v1_embedder_embedder_proto_depIdxs,
		MessageInfos:      file_v1_embedder_embedder_proto_msgTypes,
	}.Build()
	File_v1_embedder_embedder_proto = out.File
	file_v1_embedder_embedder_proto_goTypes = nil
	file_v1_embedder_embedder_proto_depIdxs = nil
}
