#!/bin/sh

if git diff HEAD^ --name-only | grep ".go$" > /dev/null; then
    # goimports
    find ./ -type f -regex ".*\.go" | xargs goimports -w

    # golangci-lint
    golangci-lint run --enable-all --disable=gochecknoglobals --exclude-use-default=false ./...

    # go build
    go build ./...
fi
