//
// Copyright (C) 2019-2026 vdaas.org vald team <vald@vdaas.org>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Command deepcopygen is a PoC: it reads the generated value types (e.g.
// values.gen.go) and emits DeepCopyInto methods in the internal/k8s/resource
// helper style (CopyPtr / CopyPtrInto / CopyPtrSliceInto / maps.Clone), so the
// generated types satisfy the resource.Base DeepCopyIntoer contract without
// controller-gen. Config types (no DeepCopyInto) are copied with CopyPtr;
// types that own references (corev1.*, nested generated structs) use *Into.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
)

type aliasInfo struct {
	pkg     string // "corev1" / "config" / ...
	isSlice bool   // type X = []pkg.Y
}

var scalars = map[string]bool{
	"bool": true, "string": true, "byte": true, "rune": true,
	"int": true, "int8": true, "int16": true, "int32": true, "int64": true,
	"uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true,
	"float32": true, "float64": true,
}

func main() {
	in := flag.String("in", "", "generated types .go file (required)")
	pkg := flag.String("package", "valdrelease", "package name")
	flag.Parse()
	if *in == "" {
		fmt.Fprintln(os.Stderr, "deepcopygen: -in required")
		os.Exit(2)
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, *in, nil, 0)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	structs := map[string]*ast.StructType{}
	aliases := map[string]aliasInfo{}
	enums := map[string]bool{}
	var order []string

	for _, d := range f.Decls {
		gd, ok := d.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, s := range gd.Specs {
			ts, ok := s.(*ast.TypeSpec)
			if !ok {
				continue
			}
			name := ts.Name.Name
			if ts.Assign != token.NoPos { // type X = ...  (alias)
				switch rhs := ts.Type.(type) {
				case *ast.SelectorExpr:
					aliases[name] = aliasInfo{pkg: exprPkg(rhs)}
				case *ast.ArrayType:
					if se, ok := rhs.Elt.(*ast.SelectorExpr); ok {
						aliases[name] = aliasInfo{pkg: exprPkg(se), isSlice: true}
					}
				}
				continue
			}
			switch t := ts.Type.(type) {
			case *ast.StructType:
				structs[name] = t
				order = append(order, name)
			case *ast.Ident:
				if scalars[t.Name] {
					enums[name] = true
				}
			}
		}
	}

	usesMaps := false
	var body bytes.Buffer
	for _, name := range order {
		fmt.Fprintf(&body, "func (in *%s) DeepCopyInto(out *%s) {\n\t*out = *in\n", name, name)
		st := structs[name]
		for _, fld := range st.Fields.List {
			if len(fld.Names) == 0 {
				continue
			}
			fn := fld.Names[0].Name
			line := fieldCopy(fn, fld.Type, structs, aliases, enums, &usesMaps)
			if line != "" {
				fmt.Fprintf(&body, "\t%s\n", line)
			}
		}
		body.WriteString("}\n\n")
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by deepcopygen (PoC). DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "package %s\n\n", *pkg)
	out.WriteString("import (\n")
	if usesMaps {
		out.WriteString("\t\"maps\"\n\n")
	}
	out.WriteString("\t\"github.com/vdaas/vald/internal/k8s/resource\"\n)\n\n")
	out.Write(body.Bytes())

	formatted, ferr := format.Source(out.Bytes())
	if ferr != nil {
		// still print unformatted for inspection
		fmt.Print(out.String())
		fmt.Fprintln(os.Stderr, "gofmt:", ferr)
		os.Exit(1)
	}
	os.Stdout.Write(formatted)
}

// elemDeepCopyable reports whether a slice element type owns references and
// provides DeepCopyInto (local struct or a non-config external type), so
// CopyPtrSliceInto is safe. Scalars, enums and config-backed elements are not.
func elemDeepCopyable(
	e ast.Expr, structs map[string]*ast.StructType, aliases map[string]aliasInfo,
) bool {
	switch t := e.(type) {
	case *ast.StarExpr:
		return elemDeepCopyable(t.X, structs, aliases)
	case *ast.Ident:
		if scalars[t.Name] {
			return false
		}
		if structs[t.Name] != nil {
			return true
		}
		if a, ok := aliases[t.Name]; ok {
			return a.pkg != "config" && a.pkg != ""
		}
		return false
	case *ast.SelectorExpr:
		return exprPkg(t) != "config"
	}
	return false
}

func exprPkg(se *ast.SelectorExpr) string {
	if id, ok := se.X.(*ast.Ident); ok {
		return id.Name
	}
	return ""
}

func fieldCopy(
	fn string,
	typ ast.Expr,
	structs map[string]*ast.StructType,
	aliases map[string]aliasInfo,
	enums map[string]bool,
	usesMaps *bool,
) string {
	switch t := typ.(type) {
	case *ast.StarExpr:
		switch e := t.X.(type) {
		case *ast.Ident:
			n := e.Name
			switch {
			case scalars[n], enums[n]:
				return fmt.Sprintf("out.%s = resource.CopyPtr(in.%s)", fn, fn)
			case structs[n] != nil:
				return fmt.Sprintf("out.%s = resource.CopyPtrInto(in.%s)", fn, fn)
			}
			if a, ok := aliases[n]; ok {
				switch {
				case a.isSlice && a.pkg != "config" && a.pkg != "": // *[]corev1.X
					return fmt.Sprintf("out.%s = resource.CopyPtrSliceInto(in.%s)", fn, fn)
				case a.isSlice: // slice of scalar / config -> shallow
					return fmt.Sprintf("out.%s = resource.CopyPtr(in.%s)", fn, fn)
				case a.pkg == "config": // external, no DeepCopyInto -> shallow value copy
					return fmt.Sprintf("out.%s = resource.CopyPtr(in.%s)", fn, fn)
				default: // corev1.* struct with DeepCopyInto
					return fmt.Sprintf("out.%s = resource.CopyPtrInto(in.%s)", fn, fn)
				}
			}
			return fmt.Sprintf("out.%s = resource.CopyPtr(in.%s)", fn, fn)
		case *ast.MapType:
			// free-form map (Issue 1): shallow copy of the map header for now.
			return fmt.Sprintf("out.%s = resource.CopyPtr(in.%s) // TODO(free-form map): deep copy", fn, fn)
		case *ast.ArrayType:
			// *[]Elem: deep-copy per element only when the element owns
			// references (struct/corev1); scalar/enum slices are shallow-copied.
			if elemDeepCopyable(e.Elt, structs, aliases) {
				return fmt.Sprintf("out.%s = resource.CopyPtrSliceInto(in.%s)", fn, fn)
			}
			return fmt.Sprintf("out.%s = resource.CopyPtr(in.%s)", fn, fn)
		}
	case *ast.MapType:
		*usesMaps = true
		return fmt.Sprintf("out.%s = maps.Clone(in.%s)", fn, fn)
	case *ast.Ident:
		if scalars[t.Name] || enums[t.Name] {
			return "" // covered by *out = *in
		}
		if structs[t.Name] != nil {
			return fmt.Sprintf("in.%s.DeepCopyInto(&out.%s)", fn, fn)
		}
	}
	return "" // value types / unhandled: covered by *out = *in
}
