apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: discovery
    app.kubernetes.io/instance: tikv
    #app.kubernetes.io/managed-by: tidb-operator
    app.kubernetes.io/name: tidb-cluster
  name: tikv-discovery
