apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: discovery
    app.kubernetes.io/instance: tikv
    #app.kubernetes.io/managed-by: tidb-operator
    app.kubernetes.io/name: tidb-cluster
  name: tikv-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tikv-discovery
subjects:
- kind: ServiceAccount
  name: tikv-discovery
