apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: tikv
    app.kubernetes.io/instance: tikv
    #app.kubernetes.io/managed-by: tidb-operator
    app.kubernetes.io/name: tidb-cluster
    app.kubernetes.io/used-by: peer
  name: tikv-tikv-peer
spec:
  ports:
    - name: peer
      protocol: TCP
      port: 20160
      targetPort: 20160
  selector:
    app.kubernetes.io/component: tikv
    app.kubernetes.io/instance: tikv
    #app.kubernetes.io/managed-by: tidb-operator
    app.kubernetes.io/name: tidb-cluster
  clusterIP: None
  publishNotReadyAddresses: true
