apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: pd
    app.kubernetes.io/instance: tikv
    #app.kubernetes.io/managed-by: tidb-operator
    app.kubernetes.io/name: tidb-cluster
    app.kubernetes.io/used-by: end-user
  name: tikv-pd
spec:
  ports:
    - name: client
      protocol: TCP
      port: 2379
      targetPort: 2379
  selector:
    app.kubernetes.io/component: pd
    app.kubernetes.io/instance: tikv
    #app.kubernetes.io/managed-by: tidb-operator
    app.kubernetes.io/name: tidb-cluster
  type: ClusterIP
