// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/tikv/pdpb.proto

package tikv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "github.com/vdaas/vald/internal/sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllStoresRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RequestHeader header = 1;
	// Do NOT return tombstone stores if set to true.
	ExcludeTombstoneStores bool `protobuf:"varint,2,opt,name=exclude_tombstone_stores,json=excludeTombstoneStores,proto3" json:"exclude_tombstone_stores,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetAllStoresRequest) Reset() {
	*x = GetAllStoresRequest{}
	mi := &file_v1_tikv_pdpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllStoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllStoresRequest) ProtoMessage() {}

func (x *GetAllStoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tikv_pdpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllStoresRequest.ProtoReflect.Descriptor instead.
func (*GetAllStoresRequest) Descriptor() ([]byte, []int) {
	return file_v1_tikv_pdpb_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllStoresRequest) GetExcludeTombstoneStores() bool {
	if x != nil {
		return x.ExcludeTombstoneStores
	}
	return false
}

type GetAllStoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stores        []*Store               `protobuf:"bytes,2,rep,name=stores,proto3" json:"stores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllStoresResponse) Reset() {
	*x = GetAllStoresResponse{}
	mi := &file_v1_tikv_pdpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllStoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllStoresResponse) ProtoMessage() {}

func (x *GetAllStoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tikv_pdpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllStoresResponse.ProtoReflect.Descriptor instead.
func (*GetAllStoresResponse) Descriptor() ([]byte, []int) {
	return file_v1_tikv_pdpb_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllStoresResponse) GetStores() []*Store {
	if x != nil {
		return x.Stores
	}
	return nil
}

type Region struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Region *Region2               `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Leader *Peer                  `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	// Leader considers that these peers are down.
	// repeated PeerStats down_peers = 3;
	// Pending peers are the peers that the leader can't consider as
	// working followers.
	PendingPeers  []*Peer `protobuf:"bytes,4,rep,name=pending_peers,json=pendingPeers,proto3" json:"pending_peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Region) Reset() {
	*x = Region{}
	mi := &file_v1_tikv_pdpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Region) ProtoMessage() {}

func (x *Region) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tikv_pdpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Region.ProtoReflect.Descriptor instead.
func (*Region) Descriptor() ([]byte, []int) {
	return file_v1_tikv_pdpb_proto_rawDescGZIP(), []int{2}
}

func (x *Region) GetRegion() *Region2 {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *Region) GetLeader() *Peer {
	if x != nil {
		return x.Leader
	}
	return nil
}

func (x *Region) GetPendingPeers() []*Peer {
	if x != nil {
		return x.PendingPeers
	}
	return nil
}

type KeyRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartKey      []byte                 `protobuf:"bytes,1,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey        []byte                 `protobuf:"bytes,2,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"` // end_key is +inf when it is empty.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRange) Reset() {
	*x = KeyRange{}
	mi := &file_v1_tikv_pdpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRange) ProtoMessage() {}

func (x *KeyRange) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tikv_pdpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRange.ProtoReflect.Descriptor instead.
func (*KeyRange) Descriptor() ([]byte, []int) {
	return file_v1_tikv_pdpb_proto_rawDescGZIP(), []int{3}
}

func (x *KeyRange) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *KeyRange) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

type BatchScanRegionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RequestHeader header = 1;
	NeedBuckets bool        `protobuf:"varint,2,opt,name=need_buckets,json=needBuckets,proto3" json:"need_buckets,omitempty"`
	Ranges      []*KeyRange `protobuf:"bytes,3,rep,name=ranges,proto3" json:"ranges,omitempty"` // the given ranges must be in order.
	Limit       int32       `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`  // limit the total number of regions to scan.
	// If contain_all_key_range is true, the output must contain all
	// key ranges in the request.
	// If the output does not contain all key ranges, the request is considered
	// failed and returns an error(REGIONS_NOT_CONTAIN_ALL_KEY_RANGE).
	ContainAllKeyRange bool `protobuf:"varint,5,opt,name=contain_all_key_range,json=containAllKeyRange,proto3" json:"contain_all_key_range,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BatchScanRegionsRequest) Reset() {
	*x = BatchScanRegionsRequest{}
	mi := &file_v1_tikv_pdpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchScanRegionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchScanRegionsRequest) ProtoMessage() {}

func (x *BatchScanRegionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tikv_pdpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchScanRegionsRequest.ProtoReflect.Descriptor instead.
func (*BatchScanRegionsRequest) Descriptor() ([]byte, []int) {
	return file_v1_tikv_pdpb_proto_rawDescGZIP(), []int{4}
}

func (x *BatchScanRegionsRequest) GetNeedBuckets() bool {
	if x != nil {
		return x.NeedBuckets
	}
	return false
}

func (x *BatchScanRegionsRequest) GetRanges() []*KeyRange {
	if x != nil {
		return x.Ranges
	}
	return nil
}

func (x *BatchScanRegionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *BatchScanRegionsRequest) GetContainAllKeyRange() bool {
	if x != nil {
		return x.ContainAllKeyRange
	}
	return false
}

type BatchScanRegionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the returned regions are flattened into a list, because the given ranges can located in the same range, we do not return duplicated regions then.
	Regions       []*Region `protobuf:"bytes,2,rep,name=regions,proto3" json:"regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchScanRegionsResponse) Reset() {
	*x = BatchScanRegionsResponse{}
	mi := &file_v1_tikv_pdpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchScanRegionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchScanRegionsResponse) ProtoMessage() {}

func (x *BatchScanRegionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tikv_pdpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchScanRegionsResponse.ProtoReflect.Descriptor instead.
func (*BatchScanRegionsResponse) Descriptor() ([]byte, []int) {
	return file_v1_tikv_pdpb_proto_rawDescGZIP(), []int{5}
}

func (x *BatchScanRegionsResponse) GetRegions() []*Region {
	if x != nil {
		return x.Regions
	}
	return nil
}

var File_v1_tikv_pdpb_proto protoreflect.FileDescriptor

const file_v1_tikv_pdpb_proto_rawDesc = "" +
	"\n" +
	"\x12v1/tikv/pdpb.proto\x12\x04pdpb\x1a\x14v1/tikv/metapb.proto\"O\n" +
	"\x13GetAllStoresRequest\x128\n" +
	"\x18exclude_tombstone_stores\x18\x02 \x01(\bR\x16excludeTombstoneStores\"=\n" +
	"\x14GetAllStoresResponse\x12%\n" +
	"\x06stores\x18\x02 \x03(\v2\r.metapb.StoreR\x06stores\"\x8a\x01\n" +
	"\x06Region\x12'\n" +
	"\x06region\x18\x01 \x01(\v2\x0f.metapb.Region2R\x06region\x12$\n" +
	"\x06leader\x18\x02 \x01(\v2\f.metapb.PeerR\x06leader\x121\n" +
	"\rpending_peers\x18\x04 \x03(\v2\f.metapb.PeerR\fpendingPeers\"@\n" +
	"\bKeyRange\x12\x1b\n" +
	"\tstart_key\x18\x01 \x01(\fR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x02 \x01(\fR\x06endKey\"\xad\x01\n" +
	"\x17BatchScanRegionsRequest\x12!\n" +
	"\fneed_buckets\x18\x02 \x01(\bR\vneedBuckets\x12&\n" +
	"\x06ranges\x18\x03 \x03(\v2\x0e.pdpb.KeyRangeR\x06ranges\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x121\n" +
	"\x15contain_all_key_range\x18\x05 \x01(\bR\x12containAllKeyRange\"B\n" +
	"\x18BatchScanRegionsResponse\x12&\n" +
	"\aregions\x18\x02 \x03(\v2\f.pdpb.RegionR\aregions2\xa2\x01\n" +
	"\x02PD\x12G\n" +
	"\fGetAllStores\x12\x19.pdpb.GetAllStoresRequest\x1a\x1a.pdpb.GetAllStoresResponse\"\x00\x12S\n" +
	"\x10BatchScanRegions\x12\x1d.pdpb.BatchScanRegionsRequest\x1a\x1e.pdpb.BatchScanRegionsResponse\"\x00B)Z'github.com/vdaas/vald/apis/grpc/v1/tikvb\x06proto3"

var (
	file_v1_tikv_pdpb_proto_rawDescOnce sync.Once
	file_v1_tikv_pdpb_proto_rawDescData []byte
)

func file_v1_tikv_pdpb_proto_rawDescGZIP() []byte {
	file_v1_tikv_pdpb_proto_rawDescOnce.Do(func() {
		file_v1_tikv_pdpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_tikv_pdpb_proto_rawDesc), len(file_v1_tikv_pdpb_proto_rawDesc)))
	})
	return file_v1_tikv_pdpb_proto_rawDescData
}

var file_v1_tikv_pdpb_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_tikv_pdpb_proto_goTypes = []any{
	(*GetAllStoresRequest)(nil),      // 0: pdpb.GetAllStoresRequest
	(*GetAllStoresResponse)(nil),     // 1: pdpb.GetAllStoresResponse
	(*Region)(nil),                   // 2: pdpb.Region
	(*KeyRange)(nil),                 // 3: pdpb.KeyRange
	(*BatchScanRegionsRequest)(nil),  // 4: pdpb.BatchScanRegionsRequest
	(*BatchScanRegionsResponse)(nil), // 5: pdpb.BatchScanRegionsResponse
	(*Store)(nil),                    // 6: metapb.Store
	(*Region2)(nil),                  // 7: metapb.Region2
	(*Peer)(nil),                     // 8: metapb.Peer
}
var file_v1_tikv_pdpb_proto_depIdxs = []int32{
	6, // 0: pdpb.GetAllStoresResponse.stores:type_name -> metapb.Store
	7, // 1: pdpb.Region.region:type_name -> metapb.Region2
	8, // 2: pdpb.Region.leader:type_name -> metapb.Peer
	8, // 3: pdpb.Region.pending_peers:type_name -> metapb.Peer
	3, // 4: pdpb.BatchScanRegionsRequest.ranges:type_name -> pdpb.KeyRange
	2, // 5: pdpb.BatchScanRegionsResponse.regions:type_name -> pdpb.Region
	0, // 6: pdpb.PD.GetAllStores:input_type -> pdpb.GetAllStoresRequest
	4, // 7: pdpb.PD.BatchScanRegions:input_type -> pdpb.BatchScanRegionsRequest
	1, // 8: pdpb.PD.GetAllStores:output_type -> pdpb.GetAllStoresResponse
	5, // 9: pdpb.PD.BatchScanRegions:output_type -> pdpb.BatchScanRegionsResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_v1_tikv_pdpb_proto_init() }
func file_v1_tikv_pdpb_proto_init() {
	if File_v1_tikv_pdpb_proto != nil {
		return
	}
	file_v1_tikv_metapb_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_tikv_pdpb_proto_rawDesc), len(file_v1_tikv_pdpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_tikv_pdpb_proto_goTypes,
		DependencyIndexes: file_v1_tikv_pdpb_proto_depIdxs,
		MessageInfos:      file_v1_tikv_pdpb_proto_msgTypes,
	}.Build()
	File_v1_tikv_pdpb_proto = out.File
	file_v1_tikv_pdpb_proto_goTypes = nil
	file_v1_tikv_pdpb_proto_depIdxs = nil
}
