// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/tikv/pdpb.proto

package tikv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "github.com/vdaas/vald/internal/sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ErrorType type = 1;
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error2) Reset() {
	*x = Error2{}
	mi := &file_v1_tikv_pdpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error2) ProtoMessage() {}

func (x *Error2) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tikv_pdpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error2.ProtoReflect.Descriptor instead.
func (*Error2) Descriptor() ([]byte, []int) {
	return file_v1_tikv_pdpb_proto_rawDescGZIP(), []int{0}
}

func (x *Error2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResponseHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cluster_id is the ID of the cluster which sent the response.
	ClusterId     uint64  `protobuf:"varint,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Error         *Error2 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseHeader) Reset() {
	*x = ResponseHeader{}
	mi := &file_v1_tikv_pdpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHeader) ProtoMessage() {}

func (x *ResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tikv_pdpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHeader.ProtoReflect.Descriptor instead.
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return file_v1_tikv_pdpb_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseHeader) GetClusterId() uint64 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *ResponseHeader) GetError() *Error2 {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetClusterInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterInfoRequest) Reset() {
	*x = GetClusterInfoRequest{}
	mi := &file_v1_tikv_pdpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterInfoRequest) ProtoMessage() {}

func (x *GetClusterInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tikv_pdpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterInfoRequest.ProtoReflect.Descriptor instead.
func (*GetClusterInfoRequest) Descriptor() ([]byte, []int) {
	return file_v1_tikv_pdpb_proto_rawDescGZIP(), []int{2}
}

func (x *GetClusterInfoRequest) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type GetClusterInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterInfoResponse) Reset() {
	*x = GetClusterInfoResponse{}
	mi := &file_v1_tikv_pdpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterInfoResponse) ProtoMessage() {}

func (x *GetClusterInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tikv_pdpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterInfoResponse.ProtoReflect.Descriptor instead.
func (*GetClusterInfoResponse) Descriptor() ([]byte, []int) {
	return file_v1_tikv_pdpb_proto_rawDescGZIP(), []int{3}
}

func (x *GetClusterInfoResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type RequestHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cluster_id is the ID of the cluster which be sent to.
	ClusterId uint64 `protobuf:"varint,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// sender_id is the ID of the sender server, also member ID or etcd ID.
	// sender_id is used in PD internal communication.
	SenderId uint64 `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// caller_id is the ID of the client which sends the request, such as tikv,
	// tidb, cdc, etc.
	CallerId string `protobuf:"bytes,3,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	// caller_component is the component of the client which sends the request,
	// such as ddl, optimizer, etc.
	CallerComponent string `protobuf:"bytes,4,opt,name=caller_component,json=callerComponent,proto3" json:"caller_component,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestHeader) Reset() {
	*x = RequestHeader{}
	mi := &file_v1_tikv_pdpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHeader) ProtoMessage() {}

func (x *RequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tikv_pdpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHeader.ProtoReflect.Descriptor instead.
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return file_v1_tikv_pdpb_proto_rawDescGZIP(), []int{4}
}

func (x *RequestHeader) GetClusterId() uint64 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *RequestHeader) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *RequestHeader) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

func (x *RequestHeader) GetCallerComponent() string {
	if x != nil {
		return x.CallerComponent
	}
	return ""
}

type GetAllStoresRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *RequestHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Do NOT return tombstone stores if set to true.
	ExcludeTombstoneStores bool `protobuf:"varint,2,opt,name=exclude_tombstone_stores,json=excludeTombstoneStores,proto3" json:"exclude_tombstone_stores,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetAllStoresRequest) Reset() {
	*x = GetAllStoresRequest{}
	mi := &file_v1_tikv_pdpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllStoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllStoresRequest) ProtoMessage() {}

func (x *GetAllStoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tikv_pdpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllStoresRequest.ProtoReflect.Descriptor instead.
func (*GetAllStoresRequest) Descriptor() ([]byte, []int) {
	return file_v1_tikv_pdpb_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllStoresRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetAllStoresRequest) GetExcludeTombstoneStores() bool {
	if x != nil {
		return x.ExcludeTombstoneStores
	}
	return false
}

type GetAllStoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Stores        []*Store               `protobuf:"bytes,2,rep,name=stores,proto3" json:"stores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllStoresResponse) Reset() {
	*x = GetAllStoresResponse{}
	mi := &file_v1_tikv_pdpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllStoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllStoresResponse) ProtoMessage() {}

func (x *GetAllStoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tikv_pdpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllStoresResponse.ProtoReflect.Descriptor instead.
func (*GetAllStoresResponse) Descriptor() ([]byte, []int) {
	return file_v1_tikv_pdpb_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllStoresResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetAllStoresResponse) GetStores() []*Store {
	if x != nil {
		return x.Stores
	}
	return nil
}

type Region struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Region *Region2               `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Leader *Peer                  `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	// Leader considers that these peers are down.
	// repeated PeerStats down_peers = 3;
	// Pending peers are the peers that the leader can't consider as
	// working followers.
	PendingPeers  []*Peer `protobuf:"bytes,4,rep,name=pending_peers,json=pendingPeers,proto3" json:"pending_peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Region) Reset() {
	*x = Region{}
	mi := &file_v1_tikv_pdpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Region) ProtoMessage() {}

func (x *Region) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tikv_pdpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Region.ProtoReflect.Descriptor instead.
func (*Region) Descriptor() ([]byte, []int) {
	return file_v1_tikv_pdpb_proto_rawDescGZIP(), []int{7}
}

func (x *Region) GetRegion() *Region2 {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *Region) GetLeader() *Peer {
	if x != nil {
		return x.Leader
	}
	return nil
}

func (x *Region) GetPendingPeers() []*Peer {
	if x != nil {
		return x.PendingPeers
	}
	return nil
}

type KeyRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartKey      []byte                 `protobuf:"bytes,1,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey        []byte                 `protobuf:"bytes,2,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"` // end_key is +inf when it is empty.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRange) Reset() {
	*x = KeyRange{}
	mi := &file_v1_tikv_pdpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRange) ProtoMessage() {}

func (x *KeyRange) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tikv_pdpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRange.ProtoReflect.Descriptor instead.
func (*KeyRange) Descriptor() ([]byte, []int) {
	return file_v1_tikv_pdpb_proto_rawDescGZIP(), []int{8}
}

func (x *KeyRange) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *KeyRange) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

type BatchScanRegionsRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Header      *RequestHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	NeedBuckets bool                   `protobuf:"varint,2,opt,name=need_buckets,json=needBuckets,proto3" json:"need_buckets,omitempty"`
	Ranges      []*KeyRange            `protobuf:"bytes,3,rep,name=ranges,proto3" json:"ranges,omitempty"` // the given ranges must be in order.
	Limit       int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`  // limit the total number of regions to scan.
	// If contain_all_key_range is true, the output must contain all
	// key ranges in the request.
	// If the output does not contain all key ranges, the request is considered
	// failed and returns an error(REGIONS_NOT_CONTAIN_ALL_KEY_RANGE).
	ContainAllKeyRange bool `protobuf:"varint,5,opt,name=contain_all_key_range,json=containAllKeyRange,proto3" json:"contain_all_key_range,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BatchScanRegionsRequest) Reset() {
	*x = BatchScanRegionsRequest{}
	mi := &file_v1_tikv_pdpb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchScanRegionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchScanRegionsRequest) ProtoMessage() {}

func (x *BatchScanRegionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tikv_pdpb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchScanRegionsRequest.ProtoReflect.Descriptor instead.
func (*BatchScanRegionsRequest) Descriptor() ([]byte, []int) {
	return file_v1_tikv_pdpb_proto_rawDescGZIP(), []int{9}
}

func (x *BatchScanRegionsRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *BatchScanRegionsRequest) GetNeedBuckets() bool {
	if x != nil {
		return x.NeedBuckets
	}
	return false
}

func (x *BatchScanRegionsRequest) GetRanges() []*KeyRange {
	if x != nil {
		return x.Ranges
	}
	return nil
}

func (x *BatchScanRegionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *BatchScanRegionsRequest) GetContainAllKeyRange() bool {
	if x != nil {
		return x.ContainAllKeyRange
	}
	return false
}

type BatchScanRegionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the returned regions are flattened into a list, because the given ranges can located in the same range, we do not return duplicated regions then.
	Regions       []*Region `protobuf:"bytes,2,rep,name=regions,proto3" json:"regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchScanRegionsResponse) Reset() {
	*x = BatchScanRegionsResponse{}
	mi := &file_v1_tikv_pdpb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchScanRegionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchScanRegionsResponse) ProtoMessage() {}

func (x *BatchScanRegionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tikv_pdpb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchScanRegionsResponse.ProtoReflect.Descriptor instead.
func (*BatchScanRegionsResponse) Descriptor() ([]byte, []int) {
	return file_v1_tikv_pdpb_proto_rawDescGZIP(), []int{10}
}

func (x *BatchScanRegionsResponse) GetRegions() []*Region {
	if x != nil {
		return x.Regions
	}
	return nil
}

var File_v1_tikv_pdpb_proto protoreflect.FileDescriptor

const file_v1_tikv_pdpb_proto_rawDesc = "" +
	"\n" +
	"\x12v1/tikv/pdpb.proto\x12\x04pdpb\x1a\x14v1/tikv/metapb.proto\"\"\n" +
	"\x06Error2\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"S\n" +
	"\x0eResponseHeader\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\x04R\tclusterId\x12\"\n" +
	"\x05error\x18\x02 \x01(\v2\f.pdpb.Error2R\x05error\"E\n" +
	"\x15GetClusterInfoRequest\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.pdpb.ResponseHeaderR\x06header\"F\n" +
	"\x16GetClusterInfoResponse\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.pdpb.ResponseHeaderR\x06header\"\x93\x01\n" +
	"\rRequestHeader\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\x04R\tclusterId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x04R\bsenderId\x12\x1b\n" +
	"\tcaller_id\x18\x03 \x01(\tR\bcallerId\x12)\n" +
	"\x10caller_component\x18\x04 \x01(\tR\x0fcallerComponent\"|\n" +
	"\x13GetAllStoresRequest\x12+\n" +
	"\x06header\x18\x01 \x01(\v2\x13.pdpb.RequestHeaderR\x06header\x128\n" +
	"\x18exclude_tombstone_stores\x18\x02 \x01(\bR\x16excludeTombstoneStores\"k\n" +
	"\x14GetAllStoresResponse\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.pdpb.ResponseHeaderR\x06header\x12%\n" +
	"\x06stores\x18\x02 \x03(\v2\r.metapb.StoreR\x06stores\"\x8a\x01\n" +
	"\x06Region\x12'\n" +
	"\x06region\x18\x01 \x01(\v2\x0f.metapb.Region2R\x06region\x12$\n" +
	"\x06leader\x18\x02 \x01(\v2\f.metapb.PeerR\x06leader\x121\n" +
	"\rpending_peers\x18\x04 \x03(\v2\f.metapb.PeerR\fpendingPeers\"@\n" +
	"\bKeyRange\x12\x1b\n" +
	"\tstart_key\x18\x01 \x01(\fR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x02 \x01(\fR\x06endKey\"\xda\x01\n" +
	"\x17BatchScanRegionsRequest\x12+\n" +
	"\x06header\x18\x01 \x01(\v2\x13.pdpb.RequestHeaderR\x06header\x12!\n" +
	"\fneed_buckets\x18\x02 \x01(\bR\vneedBuckets\x12&\n" +
	"\x06ranges\x18\x03 \x03(\v2\x0e.pdpb.KeyRangeR\x06ranges\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x121\n" +
	"\x15contain_all_key_range\x18\x05 \x01(\bR\x12containAllKeyRange\"B\n" +
	"\x18BatchScanRegionsResponse\x12&\n" +
	"\aregions\x18\x02 \x03(\v2\f.pdpb.RegionR\aregions2\xf1\x01\n" +
	"\x02PD\x12M\n" +
	"\x0eGetClusterInfo\x12\x1b.pdpb.GetClusterInfoRequest\x1a\x1c.pdpb.GetClusterInfoResponse\"\x00\x12G\n" +
	"\fGetAllStores\x12\x19.pdpb.GetAllStoresRequest\x1a\x1a.pdpb.GetAllStoresResponse\"\x00\x12S\n" +
	"\x10BatchScanRegions\x12\x1d.pdpb.BatchScanRegionsRequest\x1a\x1e.pdpb.BatchScanRegionsResponse\"\x00B)Z'github.com/vdaas/vald/apis/grpc/v1/tikvb\x06proto3"

var (
	file_v1_tikv_pdpb_proto_rawDescOnce sync.Once
	file_v1_tikv_pdpb_proto_rawDescData []byte
)

func file_v1_tikv_pdpb_proto_rawDescGZIP() []byte {
	file_v1_tikv_pdpb_proto_rawDescOnce.Do(func() {
		file_v1_tikv_pdpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_tikv_pdpb_proto_rawDesc), len(file_v1_tikv_pdpb_proto_rawDesc)))
	})
	return file_v1_tikv_pdpb_proto_rawDescData
}

var file_v1_tikv_pdpb_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_v1_tikv_pdpb_proto_goTypes = []any{
	(*Error2)(nil),                   // 0: pdpb.Error2
	(*ResponseHeader)(nil),           // 1: pdpb.ResponseHeader
	(*GetClusterInfoRequest)(nil),    // 2: pdpb.GetClusterInfoRequest
	(*GetClusterInfoResponse)(nil),   // 3: pdpb.GetClusterInfoResponse
	(*RequestHeader)(nil),            // 4: pdpb.RequestHeader
	(*GetAllStoresRequest)(nil),      // 5: pdpb.GetAllStoresRequest
	(*GetAllStoresResponse)(nil),     // 6: pdpb.GetAllStoresResponse
	(*Region)(nil),                   // 7: pdpb.Region
	(*KeyRange)(nil),                 // 8: pdpb.KeyRange
	(*BatchScanRegionsRequest)(nil),  // 9: pdpb.BatchScanRegionsRequest
	(*BatchScanRegionsResponse)(nil), // 10: pdpb.BatchScanRegionsResponse
	(*Store)(nil),                    // 11: metapb.Store
	(*Region2)(nil),                  // 12: metapb.Region2
	(*Peer)(nil),                     // 13: metapb.Peer
}
var file_v1_tikv_pdpb_proto_depIdxs = []int32{
	0,  // 0: pdpb.ResponseHeader.error:type_name -> pdpb.Error2
	1,  // 1: pdpb.GetClusterInfoRequest.header:type_name -> pdpb.ResponseHeader
	1,  // 2: pdpb.GetClusterInfoResponse.header:type_name -> pdpb.ResponseHeader
	4,  // 3: pdpb.GetAllStoresRequest.header:type_name -> pdpb.RequestHeader
	1,  // 4: pdpb.GetAllStoresResponse.header:type_name -> pdpb.ResponseHeader
	11, // 5: pdpb.GetAllStoresResponse.stores:type_name -> metapb.Store
	12, // 6: pdpb.Region.region:type_name -> metapb.Region2
	13, // 7: pdpb.Region.leader:type_name -> metapb.Peer
	13, // 8: pdpb.Region.pending_peers:type_name -> metapb.Peer
	4,  // 9: pdpb.BatchScanRegionsRequest.header:type_name -> pdpb.RequestHeader
	8,  // 10: pdpb.BatchScanRegionsRequest.ranges:type_name -> pdpb.KeyRange
	7,  // 11: pdpb.BatchScanRegionsResponse.regions:type_name -> pdpb.Region
	2,  // 12: pdpb.PD.GetClusterInfo:input_type -> pdpb.GetClusterInfoRequest
	5,  // 13: pdpb.PD.GetAllStores:input_type -> pdpb.GetAllStoresRequest
	9,  // 14: pdpb.PD.BatchScanRegions:input_type -> pdpb.BatchScanRegionsRequest
	3,  // 15: pdpb.PD.GetClusterInfo:output_type -> pdpb.GetClusterInfoResponse
	6,  // 16: pdpb.PD.GetAllStores:output_type -> pdpb.GetAllStoresResponse
	10, // 17: pdpb.PD.BatchScanRegions:output_type -> pdpb.BatchScanRegionsResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_v1_tikv_pdpb_proto_init() }
func file_v1_tikv_pdpb_proto_init() {
	if File_v1_tikv_pdpb_proto != nil {
		return
	}
	file_v1_tikv_metapb_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_tikv_pdpb_proto_rawDesc), len(file_v1_tikv_pdpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_tikv_pdpb_proto_goTypes,
		DependencyIndexes: file_v1_tikv_pdpb_proto_depIdxs,
		MessageInfos:      file_v1_tikv_pdpb_proto_msgTypes,
	}.Build()
	File_v1_tikv_pdpb_proto = out.File
	file_v1_tikv_pdpb_proto_goTypes = nil
	file_v1_tikv_pdpb_proto_depIdxs = nil
}
