//
// Copyright (C) 2019-2026 vdaas.org vald team <vald@vdaas.org>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/tikv/tikvpb.proto

package tikv

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_v1_tikv_tikvpb_proto protoreflect.FileDescriptor

const file_v1_tikv_tikvpb_proto_rawDesc = "" +
	"\n" +
	"\x14v1/tikv/tikvpb.proto\x12\x04tikv\x1a\x15v1/tikv/kvrpcpb.proto2\x8f\x03\n" +
	"\x04Tikv\x125\n" +
	"\x06RawGet\x12\x13.tikv.RawGetRequest\x1a\x14.tikv.RawGetResponse\"\x00\x12D\n" +
	"\vRawBatchGet\x12\x18.tikv.RawBatchGetRequest\x1a\x19.tikv.RawBatchGetResponse\"\x00\x125\n" +
	"\x06RawPut\x12\x13.tikv.RawPutRequest\x1a\x14.tikv.RawPutResponse\"\x00\x12D\n" +
	"\vRawBatchPut\x12\x18.tikv.RawBatchPutRequest\x1a\x19.tikv.RawBatchPutResponse\"\x00\x12>\n" +
	"\tRawDelete\x12\x16.tikv.RawDeleteRequest\x1a\x17.tikv.RawDeleteResponse\"\x00\x12M\n" +
	"\x0eRawBatchDelete\x12\x1b.tikv.RawBatchDeleteRequest\x1a\x1c.tikv.RawBatchDeleteResponse\"\x00B)Z'github.com/vdaas/vald/apis/grpc/v1/tikvb\x06proto3"

var file_v1_tikv_tikvpb_proto_goTypes = []any{
	(*RawGetRequest)(nil),          // 0: tikv.RawGetRequest
	(*RawBatchGetRequest)(nil),     // 1: tikv.RawBatchGetRequest
	(*RawPutRequest)(nil),          // 2: tikv.RawPutRequest
	(*RawBatchPutRequest)(nil),     // 3: tikv.RawBatchPutRequest
	(*RawDeleteRequest)(nil),       // 4: tikv.RawDeleteRequest
	(*RawBatchDeleteRequest)(nil),  // 5: tikv.RawBatchDeleteRequest
	(*RawGetResponse)(nil),         // 6: tikv.RawGetResponse
	(*RawBatchGetResponse)(nil),    // 7: tikv.RawBatchGetResponse
	(*RawPutResponse)(nil),         // 8: tikv.RawPutResponse
	(*RawBatchPutResponse)(nil),    // 9: tikv.RawBatchPutResponse
	(*RawDeleteResponse)(nil),      // 10: tikv.RawDeleteResponse
	(*RawBatchDeleteResponse)(nil), // 11: tikv.RawBatchDeleteResponse
}

var file_v1_tikv_tikvpb_proto_depIdxs = []int32{
	0,  // 0: tikv.Tikv.RawGet:input_type -> tikv.RawGetRequest
	1,  // 1: tikv.Tikv.RawBatchGet:input_type -> tikv.RawBatchGetRequest
	2,  // 2: tikv.Tikv.RawPut:input_type -> tikv.RawPutRequest
	3,  // 3: tikv.Tikv.RawBatchPut:input_type -> tikv.RawBatchPutRequest
	4,  // 4: tikv.Tikv.RawDelete:input_type -> tikv.RawDeleteRequest
	5,  // 5: tikv.Tikv.RawBatchDelete:input_type -> tikv.RawBatchDeleteRequest
	6,  // 6: tikv.Tikv.RawGet:output_type -> tikv.RawGetResponse
	7,  // 7: tikv.Tikv.RawBatchGet:output_type -> tikv.RawBatchGetResponse
	8,  // 8: tikv.Tikv.RawPut:output_type -> tikv.RawPutResponse
	9,  // 9: tikv.Tikv.RawBatchPut:output_type -> tikv.RawBatchPutResponse
	10, // 10: tikv.Tikv.RawDelete:output_type -> tikv.RawDeleteResponse
	11, // 11: tikv.Tikv.RawBatchDelete:output_type -> tikv.RawBatchDeleteResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_v1_tikv_tikvpb_proto_init() }
func file_v1_tikv_tikvpb_proto_init() {
	if File_v1_tikv_tikvpb_proto != nil {
		return
	}
	file_v1_tikv_kvrpcpb_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_tikv_tikvpb_proto_rawDesc), len(file_v1_tikv_tikvpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_tikv_tikvpb_proto_goTypes,
		DependencyIndexes: file_v1_tikv_tikvpb_proto_depIdxs,
	}.Build()
	File_v1_tikv_tikvpb_proto = out.File
	file_v1_tikv_tikvpb_proto_goTypes = nil
	file_v1_tikv_tikvpb_proto_depIdxs = nil
}
