#
# Copyright (C) 2019-2026 vdaas.org vald team <vald@vdaas.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: "Vald Operator Tests"
on:
  pull_request:
    paths:
      - "cmd/operator/vald/**"
      - "pkg/operator/vald/**"
      - "charts/operator/vald/**"
      - "internal/k8s/**"
      - "Makefile"
      - "Makefile.d/**"
      - ".github/workflows/vald-operator-test.yaml"
jobs:
  dump-contexts-to-log:
    timeout-minutes: 30
    permissions:
      contents: read
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: ./.github/actions/dump-context
  detect-ci-container:
    permissions:
      contents: read
    uses: ./.github/workflows/_detect-ci-container.yaml
  vald-operator-tests:
    timeout-minutes: 30
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    needs: [detect-ci-container]
    container:
      image: ghcr.io/vdaas/vald/vald-dev-container:${{ needs.detect-ci-container.outputs.TAG }}
      credentials:
        username: ${{ secrets.PACKAGE_USER }}
        password: ${{ secrets.PACKAGE_TOKEN }}
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set Git config
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Run Test
        run: |
          make test/operator/vald
